/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ErrorDetails6Payments } from '../models/errorDetails6Payments';
import {
  UnprocessableRequestmessageEnum,
} from '../models/unprocessableRequestmessageEnum';
import {
  UnprocessableRequestNameEnum,
} from '../models/unprocessableRequestNameEnum';

/**
 * Creates an instance of AuthorizationsCaptureResponse422Json
 */
interface AuthorizationsCaptureResponse422Json {
  name?: UnprocessableRequestNameEnum;
  message?: UnprocessableRequestmessageEnum;
  issues?: ErrorDetails6Payments[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  information_link?: string;
}

export class AuthorizationsCaptureResponse422JsonError extends ApiError<AuthorizationsCaptureResponse422Json> {}
