/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ErrorDetails15 } from '../models/errorDetails15';
import {
  UnprocessableRequestmessageEnum,
} from '../models/unprocessableRequestmessageEnum';
import {
  UnprocessableRequestNameEnum,
} from '../models/unprocessableRequestNameEnum';

/**
 * Creates an instance of AuthorizationsVoidResponse422Json
 */
interface AuthorizationsVoidResponse422Json {
  name?: UnprocessableRequestNameEnum;
  message?: UnprocessableRequestmessageEnum;
  issues?: ErrorDetails15[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  information_link?: string;
}

export class AuthorizationsVoidResponse422JsonError extends ApiError<AuthorizationsVoidResponse422Json> {}
