/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ErrorDetails } from '../models/errorDetails';
import {
  LinkDescriptionPaymentMethodTokens,
} from '../models/linkDescriptionPaymentMethodTokens';

/**
 * Creates an instance of Custom
 */
interface Custom {
  /** The human-readable, unique name of the error. */
  name: string;
  /** The message that describes the error. */
  message: string;
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  information_link?: string;
  /** An array of additional details about the error. */
  details?: ErrorDetails[];
  /** An array of request-related [HATEOAS links](/api/rest/responses/#hateoas-links). */
  links?: LinkDescriptionPaymentMethodTokens[];
}

export class CustomError extends ApiError<Custom> {}
