/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ErrorDetails12 } from '../models/errorDetails12';
import {
  ForbiddenRequestMessageEnum,
} from '../models/forbiddenRequestMessageEnum';
import { ForbiddenRequestNameEnum } from '../models/forbiddenRequestNameEnum';

/**
 * Creates an instance of ForbiddenError1
 */
interface ForbiddenError1 {
  name?: ForbiddenRequestNameEnum;
  message?: ForbiddenRequestMessageEnum;
  issues?: ErrorDetails12[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debug_id?: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  information_link?: string;
}

export class ForbiddenError1Error extends ApiError<ForbiddenError1> {}
