/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, validateAndMap } from '../../schema';
import {
  INVALIDACCOUNTSTATUS,
  iNVALIDACCOUNTSTATUSSchema,
} from '../iNVALIDACCOUNTSTATUS';

/** This is a container type for any-of types. */
export type UnauthorizedErrorIssue = INVALIDACCOUNTSTATUS;

export const unauthorizedErrorIssueSchema: Schema<UnauthorizedErrorIssue> = anyOf(
  [iNVALIDACCOUNTSTATUSSchema]
);

export namespace UnauthorizedErrorIssue {
  /**
  * Validation method to narrow down union type to INVALIDACCOUNTSTATUS type case.
  *
  * This is INVALID_ACCOUNT_STATUS case.
  */
  export function isINVALIDACCOUNTSTATUS(value: unknown): value is INVALIDACCOUNTSTATUS {
    const validationResult = validateAndMap(value, iNVALIDACCOUNTSTATUSSchema);
    return validationResult.errors === false;
  }
}
