/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  ActionDoesNotMatchIntentDescriptionEnum,
  actionDoesNotMatchIntentDescriptionEnumSchema,
} from './actionDoesNotMatchIntentDescriptionEnum';
import {
  ActionDoesNotMatchIntentIssueEnum,
  actionDoesNotMatchIntentIssueEnumSchema,
} from './actionDoesNotMatchIntentIssueEnum';

export interface ACTIONDOESNOTMATCHINTENT {
  issue?: ActionDoesNotMatchIntentIssueEnum;
  description?: ActionDoesNotMatchIntentDescriptionEnum;
}

export const aCTIONDOESNOTMATCHINTENTSchema: Schema<ACTIONDOESNOTMATCHINTENT> = object(
  {
    issue: ['issue', optional(actionDoesNotMatchIntentIssueEnumSchema)],
    description: [
      'description',
      optional(actionDoesNotMatchIntentDescriptionEnumSchema),
    ],
  }
);
