/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  AgreementAlreadyCancelledDescriptionEnum,
  agreementAlreadyCancelledDescriptionEnumSchema,
} from './agreementAlreadyCancelledDescriptionEnum';
import {
  AgreementAlreadyCancelledIssueEnum,
  agreementAlreadyCancelledIssueEnumSchema,
} from './agreementAlreadyCancelledIssueEnum';

export interface AGREEMENTALREADYCANCELLED {
  issue?: AgreementAlreadyCancelledIssueEnum;
  description?: AgreementAlreadyCancelledDescriptionEnum;
}

export const aGREEMENTALREADYCANCELLEDSchema: Schema<AGREEMENTALREADYCANCELLED> = object(
  {
    issue: ['issue', optional(agreementAlreadyCancelledIssueEnumSchema)],
    description: [
      'description',
      optional(agreementAlreadyCancelledDescriptionEnumSchema),
    ],
  }
);
