/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  AgreementAlreadyCancelled1DescriptionEnum,
  agreementAlreadyCancelled1DescriptionEnumSchema,
} from './agreementAlreadyCancelled1DescriptionEnum';
import {
  AgreementAlreadyCancelled1IssueEnum,
  agreementAlreadyCancelled1IssueEnumSchema,
} from './agreementAlreadyCancelled1IssueEnum';

export interface AGREEMENTALREADYCANCELLEDERROR {
  issue?: AgreementAlreadyCancelled1IssueEnum;
  description?: AgreementAlreadyCancelled1DescriptionEnum;
}

export const aGREEMENTALREADYCANCELLEDERRORSchema: Schema<AGREEMENTALREADYCANCELLEDERROR> = object(
  {
    issue: ['issue', optional(agreementAlreadyCancelled1IssueEnumSchema)],
    description: [
      'description',
      optional(agreementAlreadyCancelled1DescriptionEnumSchema),
    ],
  }
);
