/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AgreementAlreadyCancelled2Description2Enum
 */
export enum AgreementAlreadyCancelled2Description2Enum {
  EnumTheRequestedAgreementIsAlreadyCanceled = 'The requested agreement is already canceled.',
}

/**
 * Schema for AgreementAlreadyCancelled2Description2Enum
 */
export const agreementAlreadyCancelled2Description2EnumSchema: Schema<AgreementAlreadyCancelled2Description2Enum> = stringEnum(AgreementAlreadyCancelled2Description2Enum);
