/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  AgreementAlreadyCancelled2DescriptionEnum,
  agreementAlreadyCancelled2DescriptionEnumSchema,
} from './agreementAlreadyCancelled2DescriptionEnum';
import {
  AgreementAlreadyCancelled2IssueEnum,
  agreementAlreadyCancelled2IssueEnumSchema,
} from './agreementAlreadyCancelled2IssueEnum';

export interface AGREEMENTALREADYCANCELLEDRESULT {
  issue?: AgreementAlreadyCancelled2IssueEnum;
  description?: AgreementAlreadyCancelled2DescriptionEnum;
}

export const aGREEMENTALREADYCANCELLEDRESULTSchema: Schema<AGREEMENTALREADYCANCELLEDRESULT> = object(
  {
    issue: ['issue', optional(agreementAlreadyCancelled2IssueEnumSchema)],
    description: [
      'description',
      optional(agreementAlreadyCancelled2DescriptionEnumSchema),
    ],
  }
);
