/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AmountCannotBeSpecifiedIssueEnum
 */
export enum AmountCannotBeSpecifiedIssueEnum {
  AMOUNTCANNOTBESPECIFIED = 'AMOUNT_CANNOT_BE_SPECIFIED',
}

/**
 * Schema for AmountCannotBeSpecifiedIssueEnum
 */
export const amountCannotBeSpecifiedIssueEnumSchema: Schema<AmountCannotBeSpecifiedIssueEnum> = stringEnum(AmountCannotBeSpecifiedIssueEnum);
