/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AmountMismatch1Description2Enum
 */
export enum AmountMismatch1Description2Enum {
  EnumShouldEqualItemTotalTaxTotalShippingHandlingInsuranceShippingDiscountDiscount = 'Should equal item_total + tax_total + shipping + handling + insurance - shipping_discount - discount.',
}

/**
 * Schema for AmountMismatch1Description2Enum
 */
export const amountMismatch1Description2EnumSchema: Schema<AmountMismatch1Description2Enum> = stringEnum(AmountMismatch1Description2Enum);
