/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Money, moneySchema } from './money';

/** The breakdown of the amount. Breakdown provides details such as total item amount, total tax amount, shipping, handling, insurance, and discounts, if any. */
export interface AmountBreakdown {
  /** The subtotal for all items. Required if the request includes `purchase_units[].items[].unit_amount`. Must equal the sum of `(items[].unit_amount * items[].quantity)` for all items. <code>item_total.value</code> can not be a negative number. */
  itemTotal?: Money;
  /** The shipping fee for all items within a given `purchase_unit`. <code>shipping.value</code> can not be a negative number. */
  shipping?: Money;
  /** The handling fee for all items within a given `purchase_unit`. <code>handling.value</code> can not be a negative number. */
  handling?: Money;
  /** The total tax for all items. Required if the request includes `purchase_units.items.tax`. Must equal the sum of `(items[].tax * items[].quantity)` for all items. <code>tax_total.value</code> can not be a negative number. */
  taxTotal?: Money;
  /** The insurance fee for all items within a given `purchase_unit`. <code>insurance.value</code> can not be a negative number. */
  insurance?: Money;
  /** The shipping discount for all items within a given `purchase_unit`. <code>shipping_discount.value</code> can not be a negative number. */
  shippingDiscount?: Money;
  /** The discount for all items within a given `purchase_unit`. <code>discount.value</code> can not be a negative number. */
  discount?: Money;
}

export const amountBreakdownSchema: Schema<AmountBreakdown> = object({
  itemTotal: ['item_total', optional(lazy(() => moneySchema))],
  shipping: ['shipping', optional(lazy(() => moneySchema))],
  handling: ['handling', optional(lazy(() => moneySchema))],
  taxTotal: ['tax_total', optional(lazy(() => moneySchema))],
  insurance: ['insurance', optional(lazy(() => moneySchema))],
  shippingDiscount: ['shipping_discount', optional(lazy(() => moneySchema))],
  discount: ['discount', optional(lazy(() => moneySchema))],
});
