/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AmountMismatch1IssueEnum
 */
export enum AmountMismatch1IssueEnum {
  AMOUNTMISMATCH = 'AMOUNT_MISMATCH',
}

/**
 * Schema for AmountMismatch1IssueEnum
 */
export const amountMismatch1IssueEnumSchema: Schema<AmountMismatch1IssueEnum> = stringEnum(AmountMismatch1IssueEnum);
