/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { AmountBreakdown, amountBreakdownSchema } from './amountBreakdown';

export interface AmountBreakdownDetail {
  /** The breakdown of the amount. Breakdown provides details such as total item amount, total tax amount, shipping, handling, insurance, and discounts, if any. */
  breakdown?: AmountBreakdown;
}

export const amountBreakdownDetailSchema: Schema<AmountBreakdownDetail> = object(
  { breakdown: ['breakdown', optional(lazy(() => amountBreakdownSchema))] }
);
