/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ApplePayAmountMismatch2IssueEnum
 */
export enum ApplePayAmountMismatch2IssueEnum {
  APPLEPAYAMOUNTMISMATCH = 'APPLE_PAY_AMOUNT_MISMATCH',
}

/**
 * Schema for ApplePayAmountMismatch2IssueEnum
 */
export const applePayAmountMismatch2IssueEnumSchema: Schema<ApplePayAmountMismatch2IssueEnum> = stringEnum(ApplePayAmountMismatch2IssueEnum);
