/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ApplePayAmountMismatch3DescriptionEnum
 */
export enum ApplePayAmountMismatch3DescriptionEnum {
  EnumTheAmountSpecifiedInTheOrderShouldMatchTheAmountThatWasViewedAndAuthorizedByThePayerbuyerOnApplePayIfTheAmountHasChangedPleaseRedirectTheBuyerToAuthorizeTheOrderAgainViaApplePay = 'The \'amount\' specified in the Order should match the amount that was viewed and authorized by the payer/buyer on Apple Pay. If the amount has changed, please redirect the buyer to authorize the order again via Apple Pay.',
}

/**
 * Schema for ApplePayAmountMismatch3DescriptionEnum
 */
export const applePayAmountMismatch3DescriptionEnumSchema: Schema<ApplePayAmountMismatch3DescriptionEnum> = stringEnum(ApplePayAmountMismatch3DescriptionEnum);
