/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AuthorizationAmountExceededDescriptionEnum
 */
export enum AuthorizationAmountExceededDescriptionEnum {
  EnumAuthorizationAmountSpecifiedExceededAllowableLimitSpecifyADifferentAmountAndTryTheRequestAgainAlternatelyContactCustomerSupportToIncreaseYourLimitsLocalRegulationsEgInPSD2CountriesProhibitOveragesAboveTheAmountAuthorizedByThePayer = 'Authorization amount specified exceeded allowable limit. Specify a different amount and try the request again. Alternately, contact Customer Support to increase your limits. Local regulations (e.g. in PSD2 countries) prohibit overages above the amount authorized by the payer.',
}

/**
 * Schema for AuthorizationAmountExceededDescriptionEnum
 */
export const authorizationAmountExceededDescriptionEnumSchema: Schema<AuthorizationAmountExceededDescriptionEnum> = stringEnum(AuthorizationAmountExceededDescriptionEnum);
