/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  AuhorizationStatusDetailsPayments,
  auhorizationStatusDetailsPaymentsSchema,
} from './auhorizationStatusDetailsPayments';
import {
  AuthorizedPaymentStatusEnum,
  authorizedPaymentStatusEnumSchema,
} from './authorizedPaymentStatusEnum';

/** The status fields for an authorized payment. */
export interface AuthorizationStatusPayments {
  /** The status for the authorized payment. */
  status?: AuthorizedPaymentStatusEnum;
  /** The details of the authorized order pending status. */
  statusDetails?: AuhorizationStatusDetailsPayments;
}

export const authorizationStatusPaymentsSchema: Schema<AuthorizationStatusPayments> = object(
  {
    status: ['status', optional(authorizedPaymentStatusEnumSchema)],
    statusDetails: [
      'status_details',
      optional(lazy(() => auhorizationStatusDetailsPaymentsSchema)),
    ],
  }
);
