/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AuthorizationsVoid422IssuesItemsAnyof2IssueEnum
 */
export enum AuthorizationsVoid422IssuesItemsAnyof2IssueEnum {
  CANNOTBEVOIDED = 'CANNOT_BE_VOIDED',
}

/**
 * Schema for AuthorizationsVoid422IssuesItemsAnyof2IssueEnum
 */
export const authorizationsVoid422IssuesItemsAnyof2IssueEnumSchema: Schema<AuthorizationsVoid422IssuesItemsAnyof2IssueEnum> = stringEnum(AuthorizationsVoid422IssuesItemsAnyof2IssueEnum);
