/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InvalidCurrencyCodeDescriptionPaymentsEnum,
  invalidCurrencyCodeDescriptionPaymentsEnumSchema,
} from './invalidCurrencyCodeDescriptionPaymentsEnum';
import {
  InvalidCurrencyCodeIssueEnum,
  invalidCurrencyCodeIssueEnumSchema,
} from './invalidCurrencyCodeIssueEnum';

export interface Authorizationsreauthorize422issuesItems {
  issue?: InvalidCurrencyCodeIssueEnum;
  description?: InvalidCurrencyCodeDescriptionPaymentsEnum;
}

export const authorizationsreauthorize422issuesItemsSchema: Schema<Authorizationsreauthorize422issuesItems> = object(
  {
    issue: ['issue', optional(invalidCurrencyCodeIssueEnumSchema)],
    description: [
      'description',
      optional(invalidCurrencyCodeDescriptionPaymentsEnumSchema),
    ],
  }
);
