/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  AuthorizationCurrencyMismatchDescriptionEnum,
  authorizationCurrencyMismatchDescriptionEnumSchema,
} from './authorizationCurrencyMismatchDescriptionEnum';
import {
  AuthorizationCurrencyMismatchIssueEnum,
  authorizationCurrencyMismatchIssueEnumSchema,
} from './authorizationCurrencyMismatchIssueEnum';

export interface AUTHORIZATIONCURRENCYMISMATCH {
  issue?: AuthorizationCurrencyMismatchIssueEnum;
  description?: AuthorizationCurrencyMismatchDescriptionEnum;
}

export const aUTHORIZATIONCURRENCYMISMATCHSchema: Schema<AUTHORIZATIONCURRENCYMISMATCH> = object(
  {
    issue: ['issue', optional(authorizationCurrencyMismatchIssueEnumSchema)],
    description: [
      'description',
      optional(authorizationCurrencyMismatchDescriptionEnumSchema),
    ],
  }
);
