/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  AuthCaptureNotEnabledDescriptionEnum,
  authCaptureNotEnabledDescriptionEnumSchema,
} from './authCaptureNotEnabledDescriptionEnum';
import {
  AuthCaptureNotEnabledIssueEnum,
  authCaptureNotEnabledIssueEnumSchema,
} from './authCaptureNotEnabledIssueEnum';

export interface AUTHCAPTURENOTENABLED {
  issue?: AuthCaptureNotEnabledIssueEnum;
  description?: AuthCaptureNotEnabledDescriptionEnum;
}

export const aUTHCAPTURENOTENABLEDSchema: Schema<AUTHCAPTURENOTENABLED> = object(
  {
    issue: ['issue', optional(authCaptureNotEnabledIssueEnumSchema)],
    description: [
      'description',
      optional(authCaptureNotEnabledDescriptionEnumSchema),
    ],
  }
);
