/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AuthorizationAlreadyCapturedDescriptionEnum
 */
export enum AuthorizationAlreadyCapturedDescriptionEnum {
  EnumAuthorizationHasPreviouslyBeenCaptured = 'Authorization has previously been captured.',
}

/**
 * Schema for AuthorizationAlreadyCapturedDescriptionEnum
 */
export const authorizationAlreadyCapturedDescriptionEnumSchema: Schema<AuthorizationAlreadyCapturedDescriptionEnum> = stringEnum(AuthorizationAlreadyCapturedDescriptionEnum);
