/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AuthorizationsVoid422IssuesItemsAnyof1DescriptionEnum
 */
export enum AuthorizationsVoid422IssuesItemsAnyof1DescriptionEnum {
  EnumAuthorizationHasBeenPreviouslyVoidedAndHenceCannotBeVoidedAgain = 'Authorization has been previously voided and hence cannot be voided again.',
}

/**
 * Schema for AuthorizationsVoid422IssuesItemsAnyof1DescriptionEnum
 */
export const authorizationsVoid422IssuesItemsAnyof1DescriptionEnumSchema: Schema<AuthorizationsVoid422IssuesItemsAnyof1DescriptionEnum> = stringEnum(AuthorizationsVoid422IssuesItemsAnyof1DescriptionEnum);
