/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  PaymentSourceDefinition,
  paymentSourceDefinitionSchema,
} from './paymentSourceDefinition';

/** The authorization of an order request. */
export interface AuthorizeRequest {
  /** The source of payment for the order, which can be a token or a card. Use this object only if you have not redirected the user after order creation to approve the payment. In such cases, the user-selected payment method in the PayPal flow is implicitly used. */
  paymentSource?: PaymentSourceDefinition;
}

export const authorizeRequestSchema: Schema<AuthorizeRequest> = object({
  paymentSource: [
    'payment_source',
    optional(lazy(() => paymentSourceDefinitionSchema)),
  ],
});
