/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for AuthorizationAmountExceededIssueEnum
 */
export enum AuthorizationAmountExceededIssueEnum {
  AUTHORIZATIONAMOUNTEXCEEDED = 'AUTHORIZATION_AMOUNT_EXCEEDED',
}

/**
 * Schema for AuthorizationAmountExceededIssueEnum
 */
export const authorizationAmountExceededIssueEnumSchema: Schema<AuthorizationAmountExceededIssueEnum> = stringEnum(AuthorizationAmountExceededIssueEnum);
