/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  AuthorizationExpiredDescriptionEnum,
  authorizationExpiredDescriptionEnumSchema,
} from './authorizationExpiredDescriptionEnum';
import {
  AuthorizationExpiredIssueEnum,
  authorizationExpiredIssueEnumSchema,
} from './authorizationExpiredIssueEnum';

export interface AUTHORIZATIONEXPIRED {
  issue?: AuthorizationExpiredIssueEnum;
  description?: AuthorizationExpiredDescriptionEnum;
}

export const aUTHORIZATIONEXPIREDSchema: Schema<AUTHORIZATIONEXPIRED> = object({
  issue: ['issue', optional(authorizationExpiredIssueEnumSchema)],
  description: [
    'description',
    optional(authorizationExpiredDescriptionEnumSchema),
  ],
});
