/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  BadRequestIssue,
  badRequestIssueSchema,
} from './containers/badRequestIssue';

export interface BadRequestError {
  issues?: BadRequestIssue[];
}

export const badRequestErrorSchema: Schema<BadRequestError> = object({
  issues: ['issues', optional(array(lazy(() => badRequestIssueSchema)))],
});
