/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Badrequest400errorresponseIssuesItemsAnyof3IssueEnum
 */
export enum Badrequest400errorresponseIssuesItemsAnyof3IssueEnum {
  INVALIDSTRINGMAXLENGTH = 'INVALID_STRING_MAX_LENGTH',
}

/**
 * Schema for Badrequest400errorresponseIssuesItemsAnyof3IssueEnum
 */
export const badrequest400errorresponseIssuesItemsAnyof3IssueEnumSchema: Schema<Badrequest400errorresponseIssuesItemsAnyof3IssueEnum> = stringEnum(Badrequest400errorresponseIssuesItemsAnyof3IssueEnum);
