/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  BillingAgreementNotFoundDescriptionEnum,
  billingAgreementNotFoundDescriptionEnumSchema,
} from './billingAgreementNotFoundDescriptionEnum';
import {
  BillingAgreementNotFoundIssueEnum,
  billingAgreementNotFoundIssueEnumSchema,
} from './billingAgreementNotFoundIssueEnum';

export interface BILLINGAGREEMENTNOTFOUND {
  issue?: BillingAgreementNotFoundIssueEnum;
  description?: BillingAgreementNotFoundDescriptionEnum;
}

export const bILLINGAGREEMENTNOTFOUNDSchema: Schema<BILLINGAGREEMENTNOTFOUND> = object(
  {
    issue: ['issue', optional(billingAgreementNotFoundIssueEnumSchema)],
    description: [
      'description',
      optional(billingAgreementNotFoundDescriptionEnumSchema),
    ],
  }
);
