/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  BillingAgreementIdMismatchDescriptionEnum,
  billingAgreementIdMismatchDescriptionEnumSchema,
} from './billingAgreementIdMismatchDescriptionEnum';
import {
  BillingAgreementIdMismatchIssueEnum,
  billingAgreementIdMismatchIssueEnumSchema,
} from './billingAgreementIdMismatchIssueEnum';

export interface BILLINGAGREEMENTIDMISMATCH {
  issue?: BillingAgreementIdMismatchIssueEnum;
  description?: BillingAgreementIdMismatchDescriptionEnum;
}

export const bILLINGAGREEMENTIDMISMATCHSchema: Schema<BILLINGAGREEMENTIDMISMATCH> = object(
  {
    issue: ['issue', optional(billingAgreementIdMismatchIssueEnumSchema)],
    description: [
      'description',
      optional(billingAgreementIdMismatchDescriptionEnumSchema),
    ],
  }
);
