/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  BillingAddressInvalid1DescriptionEnum,
  billingAddressInvalid1DescriptionEnumSchema,
} from './billingAddressInvalid1DescriptionEnum';
import {
  BillingAddressInvalid1IssueEnum,
  billingAddressInvalid1IssueEnumSchema,
} from './billingAddressInvalid1IssueEnum';

export interface BILLINGADDRESSINVALIDERROR {
  issue?: BillingAddressInvalid1IssueEnum;
  description?: BillingAddressInvalid1DescriptionEnum;
}

export const bILLINGADDRESSINVALIDERRORSchema: Schema<BILLINGADDRESSINVALIDERROR> = object(
  {
    issue: ['issue', optional(billingAddressInvalid1IssueEnumSchema)],
    description: [
      'description',
      optional(billingAddressInvalid1DescriptionEnumSchema),
    ],
  }
);
