/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  BLIKExperienceContext,
  bLIKExperienceContextSchema,
} from './bLIKExperienceContext';
import {
  BLIKLevel0PaymentObject,
  bLIKLevel0PaymentObjectSchema,
} from './bLIKLevel0PaymentObject';
import {
  BLIKOneClickPaymentInformation,
  bLIKOneClickPaymentInformationSchema,
} from './bLIKOneClickPaymentInformation';

/** Information needed to pay using BLIK. */
export interface BLIKPaymentInformation {
  /** The name of the account holder associated with this payment method. */
  name: string;
  /** The [two-character ISO-3166-1 country code](/docs/integration/direct/rest/country-codes/) of the bank. */
  countryCode: string;
  /** The email address of the account holder associated with this payment method. */
  email?: string;
  /** Customizes the payer experience during the approval process for the payment. */
  experienceContext?: BLIKExperienceContext;
  /** The level_0 integration flow object. */
  level0?: BLIKLevel0PaymentObject;
  /** The one-click integration flow object. */
  oneClick?: BLIKOneClickPaymentInformation;
}

export const bLIKPaymentInformationSchema: Schema<BLIKPaymentInformation> = object(
  {
    name: ['name', string()],
    countryCode: ['country_code', string()],
    email: ['email', optional(string())],
    experienceContext: [
      'experience_context',
      optional(lazy(() => bLIKExperienceContextSchema)),
    ],
    level0: ['level_0', optional(lazy(() => bLIKLevel0PaymentObjectSchema))],
    oneClick: [
      'one_click',
      optional(lazy(() => bLIKOneClickPaymentInformationSchema)),
    ],
  }
);
