/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  ExperienceContextBaseShippingPreferenceEnum,
  experienceContextBaseShippingPreferenceEnumSchema,
} from './experienceContextBaseShippingPreferenceEnum';

/** Customizes the payer experience during the approval process for the BLIK payment. */
export interface BLIKExperienceContext {
  /** The label that overrides the business name in the PayPal account on the PayPal site. The pattern is defined by an external party and supports Unicode. */
  brandName?: string;
  /** The BCP 47-formatted locale of pages that the PayPal payment experience shows. PayPal supports a five-character code. For example, `da-DK`, `he-IL`, `id-ID`, `ja-JP`, `no-NO`, `pt-BR`, `ru-RU`, `sv-SE`, `th-TH`, `zh-CN`, `zh-HK`, or `zh-TW`. */
  locale?: string;
  /** The location from which the shipping address is derived. */
  shippingPreference?: ExperienceContextBaseShippingPreferenceEnum;
  /** The URL where the customer will be redirected upon approving a payment. */
  returnUrl?: string;
  /** The URL where the customer will be redirected upon cancelling the payment approval. */
  cancelUrl?: string;
  /** The IP address of the consumer. It could be either IPv4 or IPv6. */
  consumerIp?: string;
  /** The payer's User Agent. For example, Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0). */
  consumerUserAgent?: string;
}

export const bLIKExperienceContextSchema: Schema<BLIKExperienceContext> = object(
  {
    brandName: ['brand_name', optional(string())],
    locale: ['locale', optional(string())],
    shippingPreference: [
      'shipping_preference',
      optional(experienceContextBaseShippingPreferenceEnumSchema),
    ],
    returnUrl: ['return_url', optional(string())],
    cancelUrl: ['cancel_url', optional(string())],
    consumerIp: ['consumer_ip', optional(string())],
    consumerUserAgent: ['consumer_user_agent', optional(string())],
  }
);
