/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for BlikOneClickMissingRequiredParameter1IssueEnum
 */
export enum BlikOneClickMissingRequiredParameter1IssueEnum {
  BLIKONECLICKMISSINGREQUIREDPARAMETER = 'BLIK_ONE_CLICK_MISSING_REQUIRED_PARAMETER',
}

/**
 * Schema for BlikOneClickMissingRequiredParameter1IssueEnum
 */
export const blikOneClickMissingRequiredParameter1IssueEnumSchema: Schema<BlikOneClickMissingRequiredParameter1IssueEnum> = stringEnum(BlikOneClickMissingRequiredParameter1IssueEnum);
