/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CancelUrlRequiredDescriptionEnum
 */
export enum CancelUrlRequiredDescriptionEnum {
  EnumTheCancelUrlIsRequiredWhenAttemptingToVaultThisSource = 'The cancel url is required when attempting to vault this source.',
}

/**
 * Schema for CancelUrlRequiredDescriptionEnum
 */
export const cancelUrlRequiredDescriptionEnumSchema: Schema<CancelUrlRequiredDescriptionEnum> = stringEnum(CancelUrlRequiredDescriptionEnum);
