/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CancelUrlRequired2IssueEnum
 */
export enum CancelUrlRequired2IssueEnum {
  CANCELURLREQUIRED = 'CANCEL_URL_REQUIRED',
}

/**
 * Schema for CancelUrlRequired2IssueEnum
 */
export const cancelUrlRequired2IssueEnumSchema: Schema<CancelUrlRequired2IssueEnum> = stringEnum(CancelUrlRequired2IssueEnum);
