/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CancelUrlRequired1DescriptionEnum,
  cancelUrlRequired1DescriptionEnumSchema,
} from './cancelUrlRequired1DescriptionEnum';
import {
  CancelUrlRequired1IssueEnum,
  cancelUrlRequired1IssueEnumSchema,
} from './cancelUrlRequired1IssueEnum';

export interface CANCELURLREQUIREDERROR {
  issue?: CancelUrlRequired1IssueEnum;
  description?: CancelUrlRequired1DescriptionEnum;
}

export const cANCELURLREQUIREDERRORSchema: Schema<CANCELURLREQUIREDERROR> = object(
  {
    issue: ['issue', optional(cancelUrlRequired1IssueEnumSchema)],
    description: [
      'description',
      optional(cancelUrlRequired1DescriptionEnumSchema),
    ],
  }
);
