/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CannotBeZeroOrNegative1DescriptionEnum,
  cannotBeZeroOrNegative1DescriptionEnumSchema,
} from './cannotBeZeroOrNegative1DescriptionEnum';
import {
  CannotBeZeroOrNegative1IssueEnum,
  cannotBeZeroOrNegative1IssueEnumSchema,
} from './cannotBeZeroOrNegative1IssueEnum';

export interface CannotBeZeroOrNegative1 {
  issue?: CannotBeZeroOrNegative1IssueEnum;
  description?: CannotBeZeroOrNegative1DescriptionEnum;
}

export const cannotBeZeroOrNegative1Schema: Schema<CannotBeZeroOrNegative1> = object(
  {
    issue: ['issue', optional(cannotBeZeroOrNegative1IssueEnumSchema)],
    description: [
      'description',
      optional(cannotBeZeroOrNegative1DescriptionEnumSchema),
    ],
  }
);
