/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CaptureStatusReasonEnum,
  captureStatusReasonEnumSchema,
} from './captureStatusReasonEnum';

/** The details of the captured payment status. */
export interface CaptureStatusDetailsPayments {
  /** The reason why the captured payment status is `PENDING` or `DENIED`. */
  reason?: CaptureStatusReasonEnum;
}

export const captureStatusDetailsPaymentsSchema: Schema<CaptureStatusDetailsPayments> = object(
  { reason: ['reason', optional(captureStatusReasonEnumSchema)] }
);
