/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof14IssueEnum
 */
export enum CapturesRefund422IssuesItemsAnyof14IssueEnum {
  MAXNUMBEROFREFUNDSEXCEEDED = 'MAX_NUMBER_OF_REFUNDS_EXCEEDED',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof14IssueEnum
 */
export const capturesRefund422IssuesItemsAnyof14IssueEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof14IssueEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof14IssueEnum);
