/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CaptureIdNotFoundDescriptionEnum
 */
export enum CaptureIdNotFoundDescriptionEnum {
  EnumSpecifiedCaptureIDDoesNotExistCheckTheCaptureIDAndTryAgain = 'Specified capture ID does not exist. Check the capture ID and try again.',
}

/**
 * Schema for CaptureIdNotFoundDescriptionEnum
 */
export const captureIdNotFoundDescriptionEnumSchema: Schema<CaptureIdNotFoundDescriptionEnum> = stringEnum(CaptureIdNotFoundDescriptionEnum);
