/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof8IssueEnum
 */
export enum CapturesRefund422IssuesItemsAnyof8IssueEnum {
  REFUNDNOTALLOWED = 'REFUND_NOT_ALLOWED',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof8IssueEnum
 */
export const capturesRefund422IssuesItemsAnyof8IssueEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof8IssueEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof8IssueEnum);
