/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof11IssueEnum
 */
export enum CapturesRefund422IssuesItemsAnyof11IssueEnum {
  REFUNDAMOUNTTOOLOW = 'REFUND_AMOUNT_TOO_LOW',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof11IssueEnum
 */
export const capturesRefund422IssuesItemsAnyof11IssueEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof11IssueEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof11IssueEnum);
