/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof21IssueEnum
 */
export enum CapturesRefund422IssuesItemsAnyof21IssueEnum {
  TRANSACTIONDISPUTED = 'TRANSACTION_DISPUTED',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof21IssueEnum
 */
export const capturesRefund422IssuesItemsAnyof21IssueEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof21IssueEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof21IssueEnum);
