/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  CaptureStatus1Enum,
  captureStatus1EnumSchema,
} from './captureStatus1Enum';
import {
  CaptureStatusDetailsPayments,
  captureStatusDetailsPaymentsSchema,
} from './captureStatusDetailsPayments';

/** The status of a captured payment. */
export interface CaptureStatusPayments {
  /** The status of the captured payment. */
  status?: CaptureStatus1Enum;
  /** The details of the captured payment status. */
  statusDetails?: CaptureStatusDetailsPayments;
}

export const captureStatusPaymentsSchema: Schema<CaptureStatusPayments> = object(
  {
    status: ['status', optional(captureStatus1EnumSchema)],
    statusDetails: [
      'status_details',
      optional(lazy(() => captureStatusDetailsPaymentsSchema)),
    ],
  }
);
