/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof14DescriptionEnum
 */
export enum CapturesRefund422IssuesItemsAnyof14DescriptionEnum {
  EnumYouHaveExceededTheMaximumNumberOfRefundAttemptsForThisCapture = 'You have exceeded the maximum number of refund attempts for this capture.',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof14DescriptionEnum
 */
export const capturesRefund422IssuesItemsAnyof14DescriptionEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof14DescriptionEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof14DescriptionEnum);
