/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof10IssueEnum
 */
export enum CapturesRefund422IssuesItemsAnyof10IssueEnum {
  REFUNDAMOUNTEXCEEDED = 'REFUND_AMOUNT_EXCEEDED',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof10IssueEnum
 */
export const capturesRefund422IssuesItemsAnyof10IssueEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof10IssueEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof10IssueEnum);
