/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof23DescriptionEnum
 */
export enum CapturesRefund422IssuesItemsAnyof23DescriptionEnum {
  EnumThisRefundCanOnlyBeProcessedByTheAPICallerThatHadCapturedTheTransactionIfYouFacilitateYourTransactionsViaAPlatformpartnerPleaseInitiateARefundThroughThem = 'This refund can only be processed by the API caller that had \'captured\' the transaction. If you facilitate your transactions via a platform/partner, please initiate a refund through them.',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof23DescriptionEnum
 */
export const capturesRefund422IssuesItemsAnyof23DescriptionEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof23DescriptionEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof23DescriptionEnum);
