/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof7DescriptionEnum
 */
export enum CapturesRefund422IssuesItemsAnyof7DescriptionEnum {
  EnumRefundMustBeInTheSameCurrencyAsTheCapture = 'Refund must be in the same currency as the capture',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof7DescriptionEnum
 */
export const capturesRefund422IssuesItemsAnyof7DescriptionEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof7DescriptionEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof7DescriptionEnum);
