/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CapturesRefund422IssuesItemsAnyof6DescriptionEnum
 */
export enum CapturesRefund422IssuesItemsAnyof6DescriptionEnum {
  EnumTheCaptureHasAlreadyBeenFullyRefunded = 'The capture has already been fully refunded',
}

/**
 * Schema for CapturesRefund422IssuesItemsAnyof6DescriptionEnum
 */
export const capturesRefund422IssuesItemsAnyof6DescriptionEnumSchema: Schema<CapturesRefund422IssuesItemsAnyof6DescriptionEnum> = stringEnum(CapturesRefund422IssuesItemsAnyof6DescriptionEnum);
