/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CaptureWithChargebackNotUsableDescEnum
 */
export enum CaptureWithChargebackNotUsableDescEnum {
  EnumTheCaptureReferencedByPreviousTransactionReferenceHasAChargebackAndHenceCannotBeUsedForThisOrderPleaseUseAPreviousTransactionReferenceWhichDoesNotHaveAChargeback = 'The capture referenced by `previous_transaction_reference` has a chargeback and hence cannot be used for this order. Please use a `previous_transaction_reference` which does not have a chargeback.',
}

/**
 * Schema for CaptureWithChargebackNotUsableDescEnum
 */
export const captureWithChargebackNotUsableDescEnumSchema: Schema<CaptureWithChargebackNotUsableDescEnum> = stringEnum(CaptureWithChargebackNotUsableDescEnum);
