/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string, unknown } from '../schema';
import { Money, moneySchema } from './money';
import {
  ProcessorResponsePaymentMethodTokens,
  processorResponsePaymentMethodTokensSchema,
} from './processorResponsePaymentMethodTokens';

/** Card Verification details including the authorization details and 3D SECURE details. */
export interface CardVerificationDetails {
  /** Transaction Identifier as given by the network to indicate a previously executed CIT authorization. Only present when authorization is successful for a verification. */
  networkTransactionId?: string;
  /** The date and time when the instrument was verified. */
  time?: string;
  /** The amount used for card verification. */
  amount?: Money;
  /** The processor information. */
  processorResponse?: ProcessorResponsePaymentMethodTokens;
  threeDSecure?: unknown;
}

export const cardVerificationDetailsSchema: Schema<CardVerificationDetails> = object(
  {
    networkTransactionId: ['network_transaction_id', optional(string())],
    time: ['time', optional(string())],
    amount: ['amount', optional(lazy(() => moneySchema))],
    processorResponse: [
      'processor_response',
      optional(lazy(() => processorResponsePaymentMethodTokensSchema)),
    ],
    threeDSecure: ['three_d_secure', optional(unknown())],
  }
);
