/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CardTypeNotSupportedDescriptionEnum,
  cardTypeNotSupportedDescriptionEnumSchema,
} from './cardTypeNotSupportedDescriptionEnum';
import {
  CardTypeNotSupportedIssueEnum,
  cardTypeNotSupportedIssueEnumSchema,
} from './cardTypeNotSupportedIssueEnum';

export interface CARDTYPENOTSUPPORTED {
  issue?: CardTypeNotSupportedIssueEnum;
  description?: CardTypeNotSupportedDescriptionEnum;
}

export const cARDTYPENOTSUPPORTEDSchema: Schema<CARDTYPENOTSUPPORTED> = object({
  issue: ['issue', optional(cardTypeNotSupportedIssueEnumSchema)],
  description: [
    'description',
    optional(cardTypeNotSupportedDescriptionEnumSchema),
  ],
});
