/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardNumberRequired2IssueEnum
 */
export enum CardNumberRequired2IssueEnum {
  CARDNUMBERREQUIRED = 'CARD_NUMBER_REQUIRED',
}

/**
 * Schema for CardNumberRequired2IssueEnum
 */
export const cardNumberRequired2IssueEnumSchema: Schema<CardNumberRequired2IssueEnum> = stringEnum(CardNumberRequired2IssueEnum);
