/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardExpired1IssueEnum
 */
export enum CardExpired1IssueEnum {
  CARDEXPIRED = 'CARD_EXPIRED',
}

/**
 * Schema for CardExpired1IssueEnum
 */
export const cardExpired1IssueEnumSchema: Schema<CardExpired1IssueEnum> = stringEnum(CardExpired1IssueEnum);
