/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CardBrandNotSupportedDescriptionEnum
 */
export enum CardBrandNotSupportedDescriptionEnum {
  EnumProcessingOfThisCardBrandIsNotSupportedPleaseUseAnotherCardToContinueWithThisTransaction = 'Processing of this card brand is not supported. Please use another card to continue with this transaction.',
}

/**
 * Schema for CardBrandNotSupportedDescriptionEnum
 */
export const cardBrandNotSupportedDescriptionEnumSchema: Schema<CardBrandNotSupportedDescriptionEnum> = stringEnum(CardBrandNotSupportedDescriptionEnum);
