/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CityRequired1DescriptionEnum,
  cityRequired1DescriptionEnumSchema,
} from './cityRequired1DescriptionEnum';
import {
  CityRequired1IssueEnum,
  cityRequired1IssueEnumSchema,
} from './cityRequired1IssueEnum';

export interface CityRequired1 {
  issue?: CityRequired1IssueEnum;
  description?: CityRequired1DescriptionEnum;
}

export const cityRequired1Schema: Schema<CityRequired1> = object({
  issue: ['issue', optional(cityRequired1IssueEnumSchema)],
  description: ['description', optional(cityRequired1DescriptionEnumSchema)],
});
