/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ComplianceViolation1DescriptionEnum
 */
export enum ComplianceViolation1DescriptionEnum {
  EnumTransactionIsDeclinedDueToComplianceViolation = 'Transaction is declined due to compliance violation.',
}

/**
 * Schema for ComplianceViolation1DescriptionEnum
 */
export const complianceViolation1DescriptionEnumSchema: Schema<ComplianceViolation1DescriptionEnum> = stringEnum(ComplianceViolation1DescriptionEnum);
