/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  ComplianceViolationDescriptionEnum,
  complianceViolationDescriptionEnumSchema,
} from './complianceViolationDescriptionEnum';
import {
  ComplianceViolationIssueEnum,
  complianceViolationIssueEnumSchema,
} from './complianceViolationIssueEnum';

export interface COMPLIANCEVIOLATION {
  issue?: ComplianceViolationIssueEnum;
  description?: ComplianceViolationDescriptionEnum;
}

export const cOMPLIANCEVIOLATIONSchema: Schema<COMPLIANCEVIOLATION> = object({
  issue: ['issue', optional(complianceViolationIssueEnumSchema)],
  description: [
    'description',
    optional(complianceViolationDescriptionEnumSchema),
  ],
});
