/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ComplianceViolationDescriptionEnum
 */
export enum ComplianceViolationDescriptionEnum {
  EnumTransactionIsDeclinedDueToComplianceViolation = 'Transaction is declined due to compliance violation.',
}

/**
 * Schema for ComplianceViolationDescriptionEnum
 */
export const complianceViolationDescriptionEnumSchema: Schema<ComplianceViolationDescriptionEnum> = stringEnum(ComplianceViolationDescriptionEnum);
