/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for Conflicterror409responseIssuesItemsAnyof0IssueEnum
 */
export enum Conflicterror409responseIssuesItemsAnyof0IssueEnum {
  PREVIOUSREQUESTINPROGRESS = 'PREVIOUS_REQUEST_IN_PROGRESS',
}

/**
 * Schema for Conflicterror409responseIssuesItemsAnyof0IssueEnum
 */
export const conflicterror409responseIssuesItemsAnyof0IssueEnumSchema: Schema<Conflicterror409responseIssuesItemsAnyof0IssueEnum> = stringEnum(Conflicterror409responseIssuesItemsAnyof0IssueEnum);
