/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CountryNotSupportedByPaymentSourceIssueEnum
 */
export enum CountryNotSupportedByPaymentSourceIssueEnum {
  COUNTRYNOTSUPPORTEDBYPAYMENTSOURCE = 'COUNTRY_NOT_SUPPORTED_BY_PAYMENT_SOURCE',
}

/**
 * Schema for CountryNotSupportedByPaymentSourceIssueEnum
 */
export const countryNotSupportedByPaymentSourceIssueEnumSchema: Schema<CountryNotSupportedByPaymentSourceIssueEnum> = stringEnum(CountryNotSupportedByPaymentSourceIssueEnum);
