/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CryptogramRequiredIssueEnum
 */
export enum CryptogramRequiredIssueEnum {
  CRYPTOGRAMREQUIRED = 'CRYPTOGRAM_REQUIRED',
}

/**
 * Schema for CryptogramRequiredIssueEnum
 */
export const cryptogramRequiredIssueEnumSchema: Schema<CryptogramRequiredIssueEnum> = stringEnum(CryptogramRequiredIssueEnum);
