/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CryptogramRequired2DescriptionEnum
 */
export enum CryptogramRequired2DescriptionEnum {
  EnumCryptogramIsRequiredIfAuthenticationMethodIsCRYPTOGRAM3DS = 'Cryptogram is required if authentication method is CRYPTOGRAM 3DS.',
}

/**
 * Schema for CryptogramRequired2DescriptionEnum
 */
export const cryptogramRequired2DescriptionEnumSchema: Schema<CryptogramRequired2DescriptionEnum> = stringEnum(CryptogramRequired2DescriptionEnum);
