/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CurrencyNotSupportedForCardTypeIssueEnum
 */
export enum CurrencyNotSupportedForCardTypeIssueEnum {
  CURRENCYNOTSUPPORTEDFORCARDTYPE = 'CURRENCY_NOT_SUPPORTED_FOR_CARD_TYPE',
}

/**
 * Schema for CurrencyNotSupportedForCardTypeIssueEnum
 */
export const currencyNotSupportedForCardTypeIssueEnumSchema: Schema<CurrencyNotSupportedForCardTypeIssueEnum> = stringEnum(CurrencyNotSupportedForCardTypeIssueEnum);
