/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CurrencyNotSupportedForBankIssueEnum
 */
export enum CurrencyNotSupportedForBankIssueEnum {
  CURRENCYNOTSUPPORTEDFORBANK = 'CURRENCY_NOT_SUPPORTED_FOR_BANK',
}

/**
 * Schema for CurrencyNotSupportedForBankIssueEnum
 */
export const currencyNotSupportedForBankIssueEnumSchema: Schema<CurrencyNotSupportedForBankIssueEnum> = stringEnum(CurrencyNotSupportedForBankIssueEnum);
