/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CurrencyNotSupportedForBank1IssueEnum
 */
export enum CurrencyNotSupportedForBank1IssueEnum {
  CURRENCYNOTSUPPORTEDFORBANK = 'CURRENCY_NOT_SUPPORTED_FOR_BANK',
}

/**
 * Schema for CurrencyNotSupportedForBank1IssueEnum
 */
export const currencyNotSupportedForBank1IssueEnumSchema: Schema<CurrencyNotSupportedForBank1IssueEnum> = stringEnum(CurrencyNotSupportedForBank1IssueEnum);
