/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CurrencyNotSupportedForCountryIssueEnum
 */
export enum CurrencyNotSupportedForCountryIssueEnum {
  CURRENCYNOTSUPPORTEDFORCOUNTRY = 'CURRENCY_NOT_SUPPORTED_FOR_COUNTRY',
}

/**
 * Schema for CurrencyNotSupportedForCountryIssueEnum
 */
export const currencyNotSupportedForCountryIssueEnumSchema: Schema<CurrencyNotSupportedForCountryIssueEnum> = stringEnum(CurrencyNotSupportedForCountryIssueEnum);
