/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CurrencyNotSupportedForBankDescriptionEnum,
  currencyNotSupportedForBankDescriptionEnumSchema,
} from './currencyNotSupportedForBankDescriptionEnum';
import {
  CurrencyNotSupportedForBankIssueEnum,
  currencyNotSupportedForBankIssueEnumSchema,
} from './currencyNotSupportedForBankIssueEnum';

export interface CURRENCYNOTSUPPORTEDFORBANK {
  issue?: CurrencyNotSupportedForBankIssueEnum;
  description?: CurrencyNotSupportedForBankDescriptionEnum;
}

export const cURRENCYNOTSUPPORTEDFORBANKSchema: Schema<CURRENCYNOTSUPPORTEDFORBANK> = object(
  {
    issue: ['issue', optional(currencyNotSupportedForBankIssueEnumSchema)],
    description: [
      'description',
      optional(currencyNotSupportedForBankDescriptionEnumSchema),
    ],
  }
);
