/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for CustomerTypeEnum
 */
export enum CustomerTypeEnum {
  CONSUMER = 'CONSUMER',
  BUSINESS = 'BUSINESS',
}

/**
 * Schema for CustomerTypeEnum
 */
export const customerTypeEnumSchema: Schema<CustomerTypeEnum> = stringEnum(CustomerTypeEnum);
