/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DecimalsNotSupportedIssueEnum
 */
export enum DecimalsNotSupportedIssueEnum {
  DECIMALSNOTSUPPORTED = 'DECIMALS_NOT_SUPPORTED',
}

/**
 * Schema for DecimalsNotSupportedIssueEnum
 */
export const decimalsNotSupportedIssueEnumSchema: Schema<DecimalsNotSupportedIssueEnum> = stringEnum(DecimalsNotSupportedIssueEnum);
