/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeclinedDueToRelatedTxn1IssueEnum
 */
export enum DeclinedDueToRelatedTxn1IssueEnum {
  DECLINEDDUETORELATEDTXN = 'DECLINED_DUE_TO_RELATED_TXN',
}

/**
 * Schema for DeclinedDueToRelatedTxn1IssueEnum
 */
export const declinedDueToRelatedTxn1IssueEnumSchema: Schema<DeclinedDueToRelatedTxn1IssueEnum> = stringEnum(DeclinedDueToRelatedTxn1IssueEnum);
