/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DeviceDataNotAvailableIssueEnum
 */
export enum DeviceDataNotAvailableIssueEnum {
  DEVICEDATANOTAVAILABLE = 'DEVICE_DATA_NOT_AVAILABLE',
}

/**
 * Schema for DeviceDataNotAvailableIssueEnum
 */
export const deviceDataNotAvailableIssueEnumSchema: Schema<DeviceDataNotAvailableIssueEnum> = stringEnum(DeviceDataNotAvailableIssueEnum);
