/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  DomesticTransactionRequired2DescriptionEnum,
  domesticTransactionRequired2DescriptionEnumSchema,
} from './domesticTransactionRequired2DescriptionEnum';
import {
  DomesticTransactionRequired2IssueEnum,
  domesticTransactionRequired2IssueEnumSchema,
} from './domesticTransactionRequired2IssueEnum';

export interface DOMESTICTRANSACTIONREQUIREDERRORRESPONSE {
  issue?: DomesticTransactionRequired2IssueEnum;
  description?: DomesticTransactionRequired2DescriptionEnum;
}

export const dOMESTICTRANSACTIONREQUIREDERRORRESPONSESchema: Schema<DOMESTICTRANSACTIONREQUIREDERRORRESPONSE> = object(
  {
    issue: ['issue', optional(domesticTransactionRequired2IssueEnumSchema)],
    description: [
      'description',
      optional(domesticTransactionRequired2DescriptionEnumSchema),
    ],
  }
);
