/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DonationItemsNotSupported1DescriptionEnum
 */
export enum DonationItemsNotSupported1DescriptionEnum {
  EnumIfPurchaseUnitHasDONATIONAsTheItemscategoryThenTheOrderCanAtMostHaveOnePurchaseUnitMultiplePurchaseUnitsAreNotSupportedIfEitherOfThemHaveAtLeastOneItemsWithCategoryAsDONATION = 'If \'purchase_unit\' has "DONATION" as the \'items.category\' then the Order can at most have one purchase_unit. Multiple purchase_units are not supported if either of them have at least one items with category as "DONATION".',
}

/**
 * Schema for DonationItemsNotSupported1DescriptionEnum
 */
export const donationItemsNotSupported1DescriptionEnumSchema: Schema<DonationItemsNotSupported1DescriptionEnum> = stringEnum(DonationItemsNotSupported1DescriptionEnum);
