/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DuplicateInvoiceIdDescriptionPaymentsEnum
 */
export enum DuplicateInvoiceIdDescriptionPaymentsEnum {
  EnumRequestedInvoiceIdHasBeenPreviouslyCapturedPossibleDuplicateTransaction = 'Requested invoice_id has been previously captured. Possible duplicate transaction.',
}

/**
 * Schema for DuplicateInvoiceIdDescriptionPaymentsEnum
 */
export const duplicateInvoiceIdDescriptionPaymentsEnumSchema: Schema<DuplicateInvoiceIdDescriptionPaymentsEnum> = stringEnum(DuplicateInvoiceIdDescriptionPaymentsEnum);
