/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DuplicateReferenceId1IssueEnum
 */
export enum DuplicateReferenceId1IssueEnum {
  DUPLICATEREFERENCEID = 'DUPLICATE_REFERENCE_ID',
}

/**
 * Schema for DuplicateReferenceId1IssueEnum
 */
export const duplicateReferenceId1IssueEnumSchema: Schema<DuplicateReferenceId1IssueEnum> = stringEnum(DuplicateReferenceId1IssueEnum);
