/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DuplicateReferenceIdIssueEnum
 */
export enum DuplicateReferenceIdIssueEnum {
  DUPLICATEREFERENCEID = 'DUPLICATE_REFERENCE_ID',
}

/**
 * Schema for DuplicateReferenceIdIssueEnum
 */
export const duplicateReferenceIdIssueEnumSchema: Schema<DuplicateReferenceIdIssueEnum> = stringEnum(DuplicateReferenceIdIssueEnum);
