/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DuplicateInvoiceId2IssueEnum
 */
export enum DuplicateInvoiceId2IssueEnum {
  DUPLICATEINVOICEID = 'DUPLICATE_INVOICE_ID',
}

/**
 * Schema for DuplicateInvoiceId2IssueEnum
 */
export const duplicateInvoiceId2IssueEnumSchema: Schema<DuplicateInvoiceId2IssueEnum> = stringEnum(DuplicateInvoiceId2IssueEnum);
