/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for DuplicateReferenceIdDescriptionEnum
 */
export enum DuplicateReferenceIdDescriptionEnum {
  EnumReferenceIdMustBeUniqueIfMultiplePurchaseUnitAreProvided = '`reference_id` must be unique if multiple `purchase_unit` are provided.',
}

/**
 * Schema for DuplicateReferenceIdDescriptionEnum
 */
export const duplicateReferenceIdDescriptionEnumSchema: Schema<DuplicateReferenceIdDescriptionEnum> = stringEnum(DuplicateReferenceIdDescriptionEnum);
