/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  EMVDataRequiredDescriptionEnum,
  eMVDataRequiredDescriptionEnumSchema,
} from './eMVDataRequiredDescriptionEnum';
import {
  EMVDataRequiredIssueEnum,
  eMVDataRequiredIssueEnumSchema,
} from './eMVDataRequiredIssueEnum';

export interface EMVDATAREQUIRED {
  issue?: EMVDataRequiredIssueEnum;
  description?: EMVDataRequiredDescriptionEnum;
}

export const eMVDATAREQUIREDSchema: Schema<EMVDATAREQUIRED> = object({
  issue: ['issue', optional(eMVDataRequiredIssueEnumSchema)],
  description: ['description', optional(eMVDataRequiredDescriptionEnumSchema)],
});
