/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  InvalidCurrencyCodeDescription3Enum,
  invalidCurrencyCodeDescription3EnumSchema,
} from './invalidCurrencyCodeDescription3Enum';

/** The error details. Required for client-side `4XX` errors. */
export interface ErrorDetails6Payments {
  /** The field that caused the error. If this field is in the body, set this value to the field's JSON pointer value. Required for client-side errors. */
  field?: string;
  /** The value of the field that caused the error. */
  value?: string;
  /** The location of the field that caused the error. Value is `body`, `path`, or `query`. */
  location?: string;
  /** The unique, fine-grained application-level error code. */
  issue: string;
  /** The human-readable description for an issue. The description can change over the lifetime of an API, so clients must not depend on this value. */
  description?: InvalidCurrencyCodeDescription3Enum;
}

export const errorDetails6PaymentsSchema: Schema<ErrorDetails6Payments> = object(
  {
    field: ['field', optional(string())],
    value: ['value', optional(string())],
    location: ['location', optional(string())],
    issue: ['issue', string()],
    description: [
      'description',
      optional(invalidCurrencyCodeDescription3EnumSchema),
    ],
  }
);
