/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Customizes the Vault creation flow experience for your customers. */
export interface ExperienceContextPaymentMethodTokens {
  /** The label that overrides the business name in the PayPal account on the PayPal site. The pattern is defined by an external party and supports Unicode. */
  brandName?: string;
  /** The BCP 47-formatted locale of pages that the PayPal vaulting experience shows. PayPal supports a five-character code. For example, `DA-DK`, `HE-IL`, `ID-ID`, `JA-JP`, `NO-NO`, `PT-BR`, `RU-RU`, `SV-SE`, `TH-TH`, `ZH-CN`, `ZH-HK`, or `ZH-TW`. */
  locale?: string;
  /** The URL where the customer is redirected after customer approves leaves the flow. It is a required field for contingency flows like PayPal wallet, 3DS. */
  returnUrl?: string;
  /** The URL where the customer is redirected after customer cancels or leaves the flow. It is a required field for contingency flows like PayPal wallet, 3DS. */
  cancelUrl?: string;
  /** The shipping preference. This only applies to PayPal payment source. */
  shippingPreference?: string;
  /** Vault Instruction on action to be performed after a successful payer approval. */
  vaultInstruction?: string;
}

export const experienceContextPaymentMethodTokensSchema: Schema<ExperienceContextPaymentMethodTokens> = object(
  {
    brandName: ['brand_name', optional(string())],
    locale: ['locale', optional(string())],
    returnUrl: ['return_url', optional(string())],
    cancelUrl: ['cancel_url', optional(string())],
    shippingPreference: ['shipping_preference', optional(string())],
    vaultInstruction: ['vault_instruction', optional(string())],
  }
);
