/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  ForbiddenErrorIssuesItems,
  forbiddenErrorIssuesItemsSchema,
} from './containers/forbiddenErrorIssuesItems';

export interface ForbiddenError {
  issues?: ForbiddenErrorIssuesItems[];
}

export const forbiddenErrorSchema: Schema<ForbiddenError> = object({
  issues: [
    'issues',
    optional(array(lazy(() => forbiddenErrorIssuesItemsSchema))),
  ],
});
