/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for GooglePayGatewayMerchantIdMismatchIssueEnum
 */
export enum GooglePayGatewayMerchantIdMismatchIssueEnum {
  GOOGLEPAYGATEWAYMERCHANTIDMISMATCH = 'GOOGLE_PAY_GATEWAY_MERCHANT_ID_MISMATCH',
}

/**
 * Schema for GooglePayGatewayMerchantIdMismatchIssueEnum
 */
export const googlePayGatewayMerchantIdMismatchIssueEnumSchema: Schema<GooglePayGatewayMerchantIdMismatchIssueEnum> = stringEnum(GooglePayGatewayMerchantIdMismatchIssueEnum);
