/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncompatibleParameterValue3DescriptionEnum
 */
export enum IncompatibleParameterValue3DescriptionEnum {
  EnumTheValueOfTheFieldIsIncompatibleredundantWithOtherFieldsInTheOrder = 'The value of the field is incompatible/redundant with other fields in the order.',
}

/**
 * Schema for IncompatibleParameterValue3DescriptionEnum
 */
export const incompatibleParameterValue3DescriptionEnumSchema: Schema<IncompatibleParameterValue3DescriptionEnum> = stringEnum(IncompatibleParameterValue3DescriptionEnum);
