/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncompatibleParameterValueDescriptionEnum
 */
export enum IncompatibleParameterValueDescriptionEnum {
  EnumTheValueOfTheFieldIsIncompatibleredundantWithOtherFieldsInTheOrder = 'The value of the field is incompatible/redundant with other fields in the order.',
}

/**
 * Schema for IncompatibleParameterValueDescriptionEnum
 */
export const incompatibleParameterValueDescriptionEnumSchema: Schema<IncompatibleParameterValueDescriptionEnum> = stringEnum(IncompatibleParameterValueDescriptionEnum);
