/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncompatibleParameterValue2IssueEnum
 */
export enum IncompatibleParameterValue2IssueEnum {
  INCOMPATIBLEPARAMETERVALUE = 'INCOMPATIBLE_PARAMETER_VALUE',
}

/**
 * Schema for IncompatibleParameterValue2IssueEnum
 */
export const incompatibleParameterValue2IssueEnumSchema: Schema<IncompatibleParameterValue2IssueEnum> = stringEnum(IncompatibleParameterValue2IssueEnum);
