/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  IncompatibleParameterValue1DescriptionEnum,
  incompatibleParameterValue1DescriptionEnumSchema,
} from './incompatibleParameterValue1DescriptionEnum';
import {
  IncompatibleParameterValue1IssueEnum,
  incompatibleParameterValue1IssueEnumSchema,
} from './incompatibleParameterValue1IssueEnum';

export interface INCOMPATIBLEPARAMETERVALUEERROR {
  issue?: IncompatibleParameterValue1IssueEnum;
  description?: IncompatibleParameterValue1DescriptionEnum;
}

export const iNCOMPATIBLEPARAMETERVALUEERRORSchema: Schema<INCOMPATIBLEPARAMETERVALUEERROR> = object(
  {
    issue: ['issue', optional(incompatibleParameterValue1IssueEnumSchema)],
    description: [
      'description',
      optional(incompatibleParameterValue1DescriptionEnumSchema),
    ],
  }
);
