/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for IncompatibleParameterValue1DescriptionEnum
 */
export enum IncompatibleParameterValue1DescriptionEnum {
  EnumTheValueOfTheFieldIsIncompatibleredundantWithOtherFieldsInTheOrder = 'The value of the field is incompatible/redundant with other fields in the order.',
}

/**
 * Schema for IncompatibleParameterValue1DescriptionEnum
 */
export const incompatibleParameterValue1DescriptionEnumSchema: Schema<IncompatibleParameterValue1DescriptionEnum> = stringEnum(IncompatibleParameterValue1DescriptionEnum);
