/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InstrumentDeclined1IssueEnum
 */
export enum InstrumentDeclined1IssueEnum {
  INSTRUMENTDECLINED = 'INSTRUMENT_DECLINED',
}

/**
 * Schema for InstrumentDeclined1IssueEnum
 */
export const instrumentDeclined1IssueEnumSchema: Schema<InstrumentDeclined1IssueEnum> = stringEnum(InstrumentDeclined1IssueEnum);
