/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InstrumentDeclined1DescriptionEnum,
  instrumentDeclined1DescriptionEnumSchema,
} from './instrumentDeclined1DescriptionEnum';
import {
  InstrumentDeclined1IssueEnum,
  instrumentDeclined1IssueEnumSchema,
} from './instrumentDeclined1IssueEnum';

export interface INSTRUMENTDECLINEDERROR {
  issue?: InstrumentDeclined1IssueEnum;
  description?: InstrumentDeclined1DescriptionEnum;
}

export const iNSTRUMENTDECLINEDERRORSchema: Schema<INSTRUMENTDECLINEDERROR> = object(
  {
    issue: ['issue', optional(instrumentDeclined1IssueEnumSchema)],
    description: [
      'description',
      optional(instrumentDeclined1DescriptionEnumSchema),
    ],
  }
);
