/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InternalServerErrorInformationLinkEnum
 */
export enum InternalServerErrorInformationLinkEnum {
  EnumHttpsdeveloperpaypalcomapiordersv2errorINTERNALSERVERERROR = 'https://developer.paypal.com/api/orders/v2/#error-INTERNAL_SERVER_ERROR',
}

/**
 * Schema for InternalServerErrorInformationLinkEnum
 */
export const internalServerErrorInformationLinkEnumSchema: Schema<InternalServerErrorInformationLinkEnum> = stringEnum(InternalServerErrorInformationLinkEnum);
