/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidFXRateIdIssueEnum
 */
export enum InvalidFXRateIdIssueEnum {
  INVALIDFXRATEID = 'INVALID_FX_RATE_ID',
}

/**
 * Schema for InvalidFXRateIdIssueEnum
 */
export const invalidFXRateIdIssueEnumSchema: Schema<InvalidFXRateIdIssueEnum> = stringEnum(InvalidFXRateIdIssueEnum);
