/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InvalidParameterValueDescriptionEnum,
  invalidParameterValueDescriptionEnumSchema,
} from './invalidParameterValueDescriptionEnum';
import {
  InvalidParameterValueIssueEnum,
  invalidParameterValueIssueEnumSchema,
} from './invalidParameterValueIssueEnum';

export interface INVALIDPARAMETERVALUE {
  issue?: InvalidParameterValueIssueEnum;
  description?: InvalidParameterValueDescriptionEnum;
}

export const iNVALIDPARAMETERVALUESchema: Schema<INVALIDPARAMETERVALUE> = object(
  {
    issue: ['issue', optional(invalidParameterValueIssueEnumSchema)],
    description: [
      'description',
      optional(invalidParameterValueDescriptionEnumSchema),
    ],
  }
);
