/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidSecurityCodeLength1IssueEnum
 */
export enum InvalidSecurityCodeLength1IssueEnum {
  INVALIDSECURITYCODELENGTH = 'INVALID_SECURITY_CODE_LENGTH',
}

/**
 * Schema for InvalidSecurityCodeLength1IssueEnum
 */
export const invalidSecurityCodeLength1IssueEnumSchema: Schema<InvalidSecurityCodeLength1IssueEnum> = stringEnum(InvalidSecurityCodeLength1IssueEnum);
