/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InvalidJsonPointerFormatDescriptionEnum,
  invalidJsonPointerFormatDescriptionEnumSchema,
} from './invalidJsonPointerFormatDescriptionEnum';
import {
  InvalidJsonPointerFormatIssueEnum,
  invalidJsonPointerFormatIssueEnumSchema,
} from './invalidJsonPointerFormatIssueEnum';

export interface INVALIDJSONPOINTERFORMAT {
  issue?: InvalidJsonPointerFormatIssueEnum;
  description?: InvalidJsonPointerFormatDescriptionEnum;
}

export const iNVALIDJSONPOINTERFORMATSchema: Schema<INVALIDJSONPOINTERFORMAT> = object(
  {
    issue: ['issue', optional(invalidJsonPointerFormatIssueEnumSchema)],
    description: [
      'description',
      optional(invalidJsonPointerFormatDescriptionEnumSchema),
    ],
  }
);
