/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidJsonPointerFormat1IssueEnum
 */
export enum InvalidJsonPointerFormat1IssueEnum {
  INVALIDJSONPOINTERFORMAT = 'INVALID_JSON_POINTER_FORMAT',
}

/**
 * Schema for InvalidJsonPointerFormat1IssueEnum
 */
export const invalidJsonPointerFormat1IssueEnumSchema: Schema<InvalidJsonPointerFormat1IssueEnum> = stringEnum(InvalidJsonPointerFormat1IssueEnum);
