/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidPlatformFeesAmount1IssueEnum
 */
export enum InvalidPlatformFeesAmount1IssueEnum {
  INVALIDPLATFORMFEESAMOUNT = 'INVALID_PLATFORM_FEES_AMOUNT',
}

/**
 * Schema for InvalidPlatformFeesAmount1IssueEnum
 */
export const invalidPlatformFeesAmount1IssueEnumSchema: Schema<InvalidPlatformFeesAmount1IssueEnum> = stringEnum(InvalidPlatformFeesAmount1IssueEnum);
