/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidParameterValueDescriptionEnum
 */
export enum InvalidParameterValueDescriptionEnum {
  EnumAParameterValueIsNotValid = 'A parameter value is not valid.',
}

/**
 * Schema for InvalidParameterValueDescriptionEnum
 */
export const invalidParameterValueDescriptionEnumSchema: Schema<InvalidParameterValueDescriptionEnum> = stringEnum(InvalidParameterValueDescriptionEnum);
