/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidSecurityCodeLength3IssueEnum
 */
export enum InvalidSecurityCodeLength3IssueEnum {
  INVALIDSECURITYCODELENGTH = 'INVALID_SECURITY_CODE_LENGTH',
}

/**
 * Schema for InvalidSecurityCodeLength3IssueEnum
 */
export const invalidSecurityCodeLength3IssueEnumSchema: Schema<InvalidSecurityCodeLength3IssueEnum> = stringEnum(InvalidSecurityCodeLength3IssueEnum);
