/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidArrayMinItemsDescriptionEnum
 */
export enum InvalidArrayMinItemsDescriptionEnum {
  EnumTheNumberOfItemsInAnArrayParameterIsTooSmall = 'The number of items in an array parameter is too small.',
}

/**
 * Schema for InvalidArrayMinItemsDescriptionEnum
 */
export const invalidArrayMinItemsDescriptionEnumSchema: Schema<InvalidArrayMinItemsDescriptionEnum> = stringEnum(InvalidArrayMinItemsDescriptionEnum);
