/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InvalidPlatformFeesAccountDescriptionEnum,
  invalidPlatformFeesAccountDescriptionEnumSchema,
} from './invalidPlatformFeesAccountDescriptionEnum';
import {
  InvalidPlatformFeesAccountIssueEnum,
  invalidPlatformFeesAccountIssueEnumSchema,
} from './invalidPlatformFeesAccountIssueEnum';

export interface INVALIDPLATFORMFEESACCOUNT {
  issue?: InvalidPlatformFeesAccountIssueEnum;
  description?: InvalidPlatformFeesAccountDescriptionEnum;
}

export const iNVALIDPLATFORMFEESACCOUNTSchema: Schema<INVALIDPLATFORMFEESACCOUNT> = object(
  {
    issue: ['issue', optional(invalidPlatformFeesAccountIssueEnumSchema)],
    description: [
      'description',
      optional(invalidPlatformFeesAccountDescriptionEnumSchema),
    ],
  }
);
