/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidSecurityCodeLength2IssueEnum
 */
export enum InvalidSecurityCodeLength2IssueEnum {
  INVALIDSECURITYCODELENGTH = 'INVALID_SECURITY_CODE_LENGTH',
}

/**
 * Schema for InvalidSecurityCodeLength2IssueEnum
 */
export const invalidSecurityCodeLength2IssueEnumSchema: Schema<InvalidSecurityCodeLength2IssueEnum> = stringEnum(InvalidSecurityCodeLength2IssueEnum);
