/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidPayeePricingTierIdDescriptionEnum
 */
export enum InvalidPayeePricingTierIdDescriptionEnum {
  EnumPleaseCheckTheValueSpecifiedOrConfirmWithYourAccountManagerThatThePayeePricingTierIdSpecifiedHasBeenSetupForTheAccount = 'Please check the value specified or confirm with your Account Manager that the \'payee_pricing_tier_id\' specified has been setup for the account.',
}

/**
 * Schema for InvalidPayeePricingTierIdDescriptionEnum
 */
export const invalidPayeePricingTierIdDescriptionEnumSchema: Schema<InvalidPayeePricingTierIdDescriptionEnum> = stringEnum(InvalidPayeePricingTierIdDescriptionEnum);
