/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InvalidSecurityCodeLength2DescriptionEnum,
  invalidSecurityCodeLength2DescriptionEnumSchema,
} from './invalidSecurityCodeLength2DescriptionEnum';
import {
  InvalidSecurityCodeLength2IssueEnum,
  invalidSecurityCodeLength2IssueEnumSchema,
} from './invalidSecurityCodeLength2IssueEnum';

export interface INVALIDSECURITYCODELENGTHRESULT {
  issue?: InvalidSecurityCodeLength2IssueEnum;
  description?: InvalidSecurityCodeLength2DescriptionEnum;
}

export const iNVALIDSECURITYCODELENGTHRESULTSchema: Schema<INVALIDSECURITYCODELENGTHRESULT> = object(
  {
    issue: ['issue', optional(invalidSecurityCodeLength2IssueEnumSchema)],
    description: [
      'description',
      optional(invalidSecurityCodeLength2DescriptionEnumSchema),
    ],
  }
);
