/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidFxRateId1IssueEnum
 */
export enum InvalidFxRateId1IssueEnum {
  INVALIDFXRATEID = 'INVALID_FX_RATE_ID',
}

/**
 * Schema for InvalidFxRateId1IssueEnum
 */
export const invalidFxRateId1IssueEnumSchema: Schema<InvalidFxRateId1IssueEnum> = stringEnum(InvalidFxRateId1IssueEnum);
