/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InvalidPreviousTransactionReferenceDescriptionEnum,
  invalidPreviousTransactionReferenceDescriptionEnumSchema,
} from './invalidPreviousTransactionReferenceDescriptionEnum';
import {
  InvalidPreviousTransactionReferenceIssueEnum,
  invalidPreviousTransactionReferenceIssueEnumSchema,
} from './invalidPreviousTransactionReferenceIssueEnum';

export interface INVALIDPREVIOUSTRANSACTIONREFERENCE {
  issue?: InvalidPreviousTransactionReferenceIssueEnum;
  description?: InvalidPreviousTransactionReferenceDescriptionEnum;
}

export const iNVALIDPREVIOUSTRANSACTIONREFERENCESchema: Schema<INVALIDPREVIOUSTRANSACTIONREFERENCE> = object(
  {
    issue: [
      'issue',
      optional(invalidPreviousTransactionReferenceIssueEnumSchema),
    ],
    description: [
      'description',
      optional(invalidPreviousTransactionReferenceDescriptionEnumSchema),
    ],
  }
);
