/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidGooglePayMerchantIdMismatchEnum
 */
export enum InvalidGooglePayMerchantIdMismatchEnum {
  EnumTheGatewayMerchantIDInGooglePayTokenIsNotValidThisCouldBeBecauseTheGatewayMerchantIdThatWasAuthorizedByPayerbuyerOnGooglePayDoesNotMatchWithTheAPICallerOfTheOrder = 'The gateway merchant ID in Google Pay token is not valid. This could be because the gateway merchant Id that was authorized by payer/buyer on Google Pay does not match with the API caller of the order.',
}

/**
 * Schema for InvalidGooglePayMerchantIdMismatchEnum
 */
export const invalidGooglePayMerchantIdMismatchEnumSchema: Schema<InvalidGooglePayMerchantIdMismatchEnum> = stringEnum(InvalidGooglePayMerchantIdMismatchEnum);
