/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  InvalidPayeePricingTierIdDescriptionEnum,
  invalidPayeePricingTierIdDescriptionEnumSchema,
} from './invalidPayeePricingTierIdDescriptionEnum';
import {
  InvalidPayeePricingTierIdIssueEnum,
  invalidPayeePricingTierIdIssueEnumSchema,
} from './invalidPayeePricingTierIdIssueEnum';

export interface INVALIDPAYEEPRICINGTIERID {
  issue?: InvalidPayeePricingTierIdIssueEnum;
  description?: InvalidPayeePricingTierIdDescriptionEnum;
}

export const iNVALIDPAYEEPRICINGTIERIDSchema: Schema<INVALIDPAYEEPRICINGTIERID> = object(
  {
    issue: ['issue', optional(invalidPayeePricingTierIdIssueEnumSchema)],
    description: [
      'description',
      optional(invalidPayeePricingTierIdDescriptionEnumSchema),
    ],
  }
);
