/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidPlatformFeesAccount1IssueEnum
 */
export enum InvalidPlatformFeesAccount1IssueEnum {
  INVALIDPLATFORMFEESACCOUNT = 'INVALID_PLATFORM_FEES_ACCOUNT',
}

/**
 * Schema for InvalidPlatformFeesAccount1IssueEnum
 */
export const invalidPlatformFeesAccount1IssueEnumSchema: Schema<InvalidPlatformFeesAccount1IssueEnum> = stringEnum(InvalidPlatformFeesAccount1IssueEnum);
