/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidJsonPointerFormatIssueEnum
 */
export enum InvalidJsonPointerFormatIssueEnum {
  INVALIDJSONPOINTERFORMAT = 'INVALID_JSON_POINTER_FORMAT',
}

/**
 * Schema for InvalidJsonPointerFormatIssueEnum
 */
export const invalidJsonPointerFormatIssueEnumSchema: Schema<InvalidJsonPointerFormatIssueEnum> = stringEnum(InvalidJsonPointerFormatIssueEnum);
