/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for InvalidFXRateIdDescriptionEnum
 */
export enum InvalidFXRateIdDescriptionEnum {
  EnumTheSpecificFXRateIDIsNotValidThisCouldBeEitherBecauseWeAreNotAbleToLookUpTheFXRateBasedOnThisIDOrItCouldBeBecauseTheIDBelongsToAnotherAPICaller = 'The specific FX Rate ID is not valid. This could be either because we are not able to look up the FX Rate based on this ID or it could be because the ID belongs to another API Caller.',
}

/**
 * Schema for InvalidFXRateIdDescriptionEnum
 */
export const invalidFXRateIdDescriptionEnumSchema: Schema<InvalidFXRateIdDescriptionEnum> = stringEnum(InvalidFXRateIdDescriptionEnum);
