/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ItemSkuMismatch1IssueEnum
 */
export enum ItemSkuMismatch1IssueEnum {
  ITEMSKUMISMATCH = 'ITEM_SKU_MISMATCH',
}

/**
 * Schema for ItemSkuMismatch1IssueEnum
 */
export const itemSkuMismatch1IssueEnumSchema: Schema<ItemSkuMismatch1IssueEnum> = stringEnum(ItemSkuMismatch1IssueEnum);
