/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ItemTotalMismatchIssueEnum
 */
export enum ItemTotalMismatchIssueEnum {
  ITEMTOTALMISMATCH = 'ITEM_TOTAL_MISMATCH',
}

/**
 * Schema for ItemTotalMismatchIssueEnum
 */
export const itemTotalMismatchIssueEnumSchema: Schema<ItemTotalMismatchIssueEnum> = stringEnum(ItemTotalMismatchIssueEnum);
