/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ItemTotalMismatch1DescriptionEnum
 */
export enum ItemTotalMismatch1DescriptionEnum {
  EnumShouldEqualSumOfUnitAmountQuantityAcrossAllItemsForAGivenPurchaseUnit = 'Should equal sum of (unit_amount * quantity) across all items for a given purchase_unit.',
}

/**
 * Schema for ItemTotalMismatch1DescriptionEnum
 */
export const itemTotalMismatch1DescriptionEnumSchema: Schema<ItemTotalMismatch1DescriptionEnum> = stringEnum(ItemTotalMismatch1DescriptionEnum);
