/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ItemTotalMismatch1IssueEnum
 */
export enum ItemTotalMismatch1IssueEnum {
  ITEMTOTALMISMATCH = 'ITEM_TOTAL_MISMATCH',
}

/**
 * Schema for ItemTotalMismatch1IssueEnum
 */
export const itemTotalMismatch1IssueEnumSchema: Schema<ItemTotalMismatch1IssueEnum> = stringEnum(ItemTotalMismatch1IssueEnum);
