/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  InternalServerErrorInformationLinkEnum,
  internalServerErrorInformationLinkEnumSchema,
} from './internalServerErrorInformationLinkEnum';
import {
  InternalServerErrorMessageEnum,
  internalServerErrorMessageEnumSchema,
} from './internalServerErrorMessageEnum';
import {
  InternalServerErrorNameEnum,
  internalServerErrorNameEnumSchema,
} from './internalServerErrorNameEnum';

/** Error response for 500 */
export interface M500ErrorPayments {
  name?: InternalServerErrorNameEnum;
  message?: InternalServerErrorMessageEnum;
  /** The PayPal internal ID. Used for correlation purposes. */
  debugId?: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  informationLink?: InternalServerErrorInformationLinkEnum;
}

export const m500ErrorPaymentsSchema: Schema<M500ErrorPayments> = object({
  name: ['name', optional(internalServerErrorNameEnumSchema)],
  message: ['message', optional(internalServerErrorMessageEnumSchema)],
  debugId: ['debug_id', optional(string())],
  informationLink: [
    'information_link',
    optional(internalServerErrorInformationLinkEnumSchema),
  ],
});
