/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';
import {
  Error503MessageEnum,
  error503MessageEnumSchema,
} from './error503MessageEnum';
import { Error503NameEnum, error503NameEnumSchema } from './error503NameEnum';

/** Error response for 503 */
export interface M503Error {
  name?: Error503NameEnum;
  message?: Error503MessageEnum;
  /** The PayPal internal ID. Used for correlation purposes. */
  debugId?: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  informationLink?: string;
}

export const m503ErrorSchema: Schema<M503Error> = object({
  name: ['name', optional(error503NameEnumSchema)],
  message: ['message', optional(error503MessageEnumSchema)],
  debugId: ['debug_id', optional(string())],
  informationLink: ['information_link', optional(string())],
});
