/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  MaxAuthorizationCountExceededDescriptionEnum,
  maxAuthorizationCountExceededDescriptionEnumSchema,
} from './maxAuthorizationCountExceededDescriptionEnum';
import {
  MaxAuthorizationCountExceededIssueEnum,
  maxAuthorizationCountExceededIssueEnumSchema,
} from './maxAuthorizationCountExceededIssueEnum';

export interface MAXAUTHORIZATIONCOUNTEXCEEDED {
  issue?: MaxAuthorizationCountExceededIssueEnum;
  description?: MaxAuthorizationCountExceededDescriptionEnum;
}

export const mAXAUTHORIZATIONCOUNTEXCEEDEDSchema: Schema<MAXAUTHORIZATIONCOUNTEXCEEDED> = object(
  {
    issue: ['issue', optional(maxAuthorizationCountExceededIssueEnumSchema)],
    description: [
      'description',
      optional(maxAuthorizationCountExceededDescriptionEnumSchema),
    ],
  }
);
