/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MaxAuthorizationCountExceededDescriptionEnum
 */
export enum MaxAuthorizationCountExceededDescriptionEnum {
  EnumMaximumNumberOfAuthorizationAllowedForTheOrderIsReachedPleaseContactCustomerSupportIfYouNeedToIncreaseYourLimit = 'Maximum number of authorization allowed for the order is reached. Please contact Customer Support if you need to increase your limit.',
}

/**
 * Schema for MaxAuthorizationCountExceededDescriptionEnum
 */
export const maxAuthorizationCountExceededDescriptionEnumSchema: Schema<MaxAuthorizationCountExceededDescriptionEnum> = stringEnum(MaxAuthorizationCountExceededDescriptionEnum);
