/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MaxCaptureCountExceededDescriptionEnum
 */
export enum MaxCaptureCountExceededDescriptionEnum {
  EnumMaxmimumNumberOfAllowableCapturesHasBeenReachedNoAdditionalCapturesArePossibleForThisAuthorizationContactCustomerServiceOrYourAccountManagerToChangeTheNumberOfCapturesForAGivenAuthorization = 'Maxmimum number of allowable captures has been reached. No additional captures are possible for this authorization. Contact Customer Service or your account manager to change the number of captures for a given authorization.',
}

/**
 * Schema for MaxCaptureCountExceededDescriptionEnum
 */
export const maxCaptureCountExceededDescriptionEnumSchema: Schema<MaxCaptureCountExceededDescriptionEnum> = stringEnum(MaxCaptureCountExceededDescriptionEnum);
