/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MaxCaptureAmountExceededDescriptionEnum
 */
export enum MaxCaptureAmountExceededDescriptionEnum {
  EnumCaptureAmountExceedsAllowableLimitPleaseContactCustomerServiceOrYourAccountManagerToRequestTheChangeToYourOverageLimitTheDefaultOverageLimitIs115WhichAllowsTheSumOfAllCapturesToBeUpTo115OfTheOrderAmountTheAbilityToOverCaptureIsSubjectedToRegulatoryApprovals = 'Capture amount exceeds allowable limit. Please contact customer service or your account manager to request the change to your overage limit. The default overage limit is 115%, which allows the sum of all captures to be up to 115% of the order amount. The ability to over capture is subjected to regulatory approvals.',
}

/**
 * Schema for MaxCaptureAmountExceededDescriptionEnum
 */
export const maxCaptureAmountExceededDescriptionEnumSchema: Schema<MaxCaptureAmountExceededDescriptionEnum> = stringEnum(MaxCaptureAmountExceededDescriptionEnum);
