/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MaxCaptureCountExceededIssueEnum
 */
export enum MaxCaptureCountExceededIssueEnum {
  MAXCAPTURECOUNTEXCEEDED = 'MAX_CAPTURE_COUNT_EXCEEDED',
}

/**
 * Schema for MaxCaptureCountExceededIssueEnum
 */
export const maxCaptureCountExceededIssueEnumSchema: Schema<MaxCaptureCountExceededIssueEnum> = stringEnum(MaxCaptureCountExceededIssueEnum);
