/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MaxNumberOfPaymentAttemptsExceededIssueEnum
 */
export enum MaxNumberOfPaymentAttemptsExceededIssueEnum {
  MAXNUMBEROFPAYMENTATTEMPTSEXCEEDED = 'MAX_NUMBER_OF_PAYMENT_ATTEMPTS_EXCEEDED',
}

/**
 * Schema for MaxNumberOfPaymentAttemptsExceededIssueEnum
 */
export const maxNumberOfPaymentAttemptsExceededIssueEnumSchema: Schema<MaxNumberOfPaymentAttemptsExceededIssueEnum> = stringEnum(MaxNumberOfPaymentAttemptsExceededIssueEnum);
