/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MerchantInitiatedWithAuthResultsEnum
 */
export enum MerchantInitiatedWithAuthResultsEnum {
  MERCHANTINITIATEDWITHAUTHENTICATIONRESULTS = 'MERCHANT_INITIATED_WITH_AUTHENTICATION_RESULTS',
}

/**
 * Schema for MerchantInitiatedWithAuthResultsEnum
 */
export const merchantInitiatedWithAuthResultsEnumSchema: Schema<MerchantInitiatedWithAuthResultsEnum> = stringEnum(MerchantInitiatedWithAuthResultsEnum);
