/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  MerchantInitiatedWithSecurityCode2DescriptionEnum,
  merchantInitiatedWithSecurityCode2DescriptionEnumSchema,
} from './merchantInitiatedWithSecurityCode2DescriptionEnum';
import {
  MerchantInitiatedWithSecurityCode2IssueEnum,
  merchantInitiatedWithSecurityCode2IssueEnumSchema,
} from './merchantInitiatedWithSecurityCode2IssueEnum';

export interface MERCHANTINITIATEDSECURITYCODEERRORRESPONSE {
  issue?: MerchantInitiatedWithSecurityCode2IssueEnum;
  description?: MerchantInitiatedWithSecurityCode2DescriptionEnum;
}

export const mERCHANTINITIATEDSECURITYCODEERRORRESPONSESchema: Schema<MERCHANTINITIATEDSECURITYCODEERRORRESPONSE> = object(
  {
    issue: [
      'issue',
      optional(merchantInitiatedWithSecurityCode2IssueEnumSchema),
    ],
    description: [
      'description',
      optional(merchantInitiatedWithSecurityCode2DescriptionEnumSchema),
    ],
  }
);
