/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  MismatchedVaultIdToPaymentSource2DescriptionEnum,
  mismatchedVaultIdToPaymentSource2DescriptionEnumSchema,
} from './mismatchedVaultIdToPaymentSource2DescriptionEnum';
import {
  MismatchedVaultIdToPaymentSource2IssueEnum,
  mismatchedVaultIdToPaymentSource2IssueEnumSchema,
} from './mismatchedVaultIdToPaymentSource2IssueEnum';

export interface MISMATCHEDVAULTIDTOPAYMENTSOURCERESULT {
  issue?: MismatchedVaultIdToPaymentSource2IssueEnum;
  description?: MismatchedVaultIdToPaymentSource2DescriptionEnum;
}

export const mISMATCHEDVAULTIDTOPAYMENTSOURCERESULTSchema: Schema<MISMATCHEDVAULTIDTOPAYMENTSOURCERESULT> = object(
  {
    issue: [
      'issue',
      optional(mismatchedVaultIdToPaymentSource2IssueEnumSchema),
    ],
    description: [
      'description',
      optional(mismatchedVaultIdToPaymentSource2DescriptionEnumSchema),
    ],
  }
);
