/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MismatchedVaultIdToPaymentSource1IssueEnum
 */
export enum MismatchedVaultIdToPaymentSource1IssueEnum {
  MISMATCHEDVAULTIDTOPAYMENTSOURCE = 'MISMATCHED_VAULT_ID_TO_PAYMENT_SOURCE',
}

/**
 * Schema for MismatchedVaultIdToPaymentSource1IssueEnum
 */
export const mismatchedVaultIdToPaymentSource1IssueEnumSchema: Schema<MismatchedVaultIdToPaymentSource1IssueEnum> = stringEnum(MismatchedVaultIdToPaymentSource1IssueEnum);
