/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MissingCryptogramDescriptionEnum
 */
export enum MissingCryptogramDescriptionEnum {
  EnumCryptogramIsMandatoryForAnyCustomerInitiatedNetworkTokenTransactions = 'Cryptogram is mandatory for any customer initiated network token transactions.',
}

/**
 * Schema for MissingCryptogramDescriptionEnum
 */
export const missingCryptogramDescriptionEnumSchema: Schema<MissingCryptogramDescriptionEnum> = stringEnum(MissingCryptogramDescriptionEnum);
