/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  MissingPreviousReference2DescriptionEnum,
  missingPreviousReference2DescriptionEnumSchema,
} from './missingPreviousReference2DescriptionEnum';
import {
  MissingPreviousReference2IssueEnum,
  missingPreviousReference2IssueEnumSchema,
} from './missingPreviousReference2IssueEnum';

export interface MISSINGPREVIOUSREFERENCERESULT {
  issue?: MissingPreviousReference2IssueEnum;
  description?: MissingPreviousReference2DescriptionEnum;
}

export const mISSINGPREVIOUSREFERENCERESULTSchema: Schema<MISSINGPREVIOUSREFERENCERESULT> = object(
  {
    issue: ['issue', optional(missingPreviousReference2IssueEnumSchema)],
    description: [
      'description',
      optional(missingPreviousReference2DescriptionEnumSchema),
    ],
  }
);
