/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MissingPickupAddressDescriptionEnum
 */
export enum MissingPickupAddressDescriptionEnum {
  EnumAPickupAddressshippingaddressIsRequiredForTheProvidedShippingtype = 'A pickup address(`shipping.address`) is required for the provided `shipping.type`.',
}

/**
 * Schema for MissingPickupAddressDescriptionEnum
 */
export const missingPickupAddressDescriptionEnumSchema: Schema<MissingPickupAddressDescriptionEnum> = stringEnum(MissingPickupAddressDescriptionEnum);
