/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  MissingPreviousReferenceDescriptionEnum,
  missingPreviousReferenceDescriptionEnumSchema,
} from './missingPreviousReferenceDescriptionEnum';
import {
  MissingPreviousReferenceIssueEnum,
  missingPreviousReferenceIssueEnumSchema,
} from './missingPreviousReferenceIssueEnum';

export interface MISSINGPREVIOUSREFERENCE {
  issue?: MissingPreviousReferenceIssueEnum;
  description?: MissingPreviousReferenceDescriptionEnum;
}

export const mISSINGPREVIOUSREFERENCESchema: Schema<MISSINGPREVIOUSREFERENCE> = object(
  {
    issue: ['issue', optional(missingPreviousReferenceIssueEnumSchema)],
    description: [
      'description',
      optional(missingPreviousReferenceDescriptionEnumSchema),
    ],
  }
);
