/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MissingRequiredParameterDescriptionPaymentsEnum
 */
export enum MissingRequiredParameterDescriptionPaymentsEnum {
  EnumARequiredFieldParameterIsMissing = 'A required field / parameter is missing.',
}

/**
 * Schema for MissingRequiredParameterDescriptionPaymentsEnum
 */
export const missingRequiredParameterDescriptionPaymentsEnumSchema: Schema<MissingRequiredParameterDescriptionPaymentsEnum> = stringEnum(MissingRequiredParameterDescriptionPaymentsEnum);
