/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  MissingCryptogram1DescriptionEnum,
  missingCryptogram1DescriptionEnumSchema,
} from './missingCryptogram1DescriptionEnum';
import {
  MissingCryptogram1IssueEnum,
  missingCryptogram1IssueEnumSchema,
} from './missingCryptogram1IssueEnum';

export interface MISSINGCRYPTOGRAMERROR {
  issue?: MissingCryptogram1IssueEnum;
  description?: MissingCryptogram1DescriptionEnum;
}

export const mISSINGCRYPTOGRAMERRORSchema: Schema<MISSINGCRYPTOGRAMERROR> = object(
  {
    issue: ['issue', optional(missingCryptogram1IssueEnumSchema)],
    description: [
      'description',
      optional(missingCryptogram1DescriptionEnumSchema),
    ],
  }
);
