/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MissingPreviousReference2IssueEnum
 */
export enum MissingPreviousReference2IssueEnum {
  MISSINGPREVIOUSREFERENCE = 'MISSING_PREVIOUS_REFERENCE',
}

/**
 * Schema for MissingPreviousReference2IssueEnum
 */
export const missingPreviousReference2IssueEnumSchema: Schema<MissingPreviousReference2IssueEnum> = stringEnum(MissingPreviousReference2IssueEnum);
