/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  MissingCryptogram3DescriptionEnum,
  missingCryptogram3DescriptionEnumSchema,
} from './missingCryptogram3DescriptionEnum';
import {
  MissingCryptogram3IssueEnum,
  missingCryptogram3IssueEnumSchema,
} from './missingCryptogram3IssueEnum';

export interface MISSINGCRYPTOGRAMERRORRESPONSE {
  issue?: MissingCryptogram3IssueEnum;
  description?: MissingCryptogram3DescriptionEnum;
}

export const mISSINGCRYPTOGRAMERRORRESPONSESchema: Schema<MISSINGCRYPTOGRAMERRORRESPONSE> = object(
  {
    issue: ['issue', optional(missingCryptogram3IssueEnumSchema)],
    description: [
      'description',
      optional(missingCryptogram3DescriptionEnumSchema),
    ],
  }
);
