/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MultipleShippingAddressNotSupportedIssueEnum
 */
export enum MultipleShippingAddressNotSupportedIssueEnum {
  MULTIPLESHIPPINGADDRESSNOTSUPPORTED = 'MULTIPLE_SHIPPING_ADDRESS_NOT_SUPPORTED',
}

/**
 * Schema for MultipleShippingAddressNotSupportedIssueEnum
 */
export const multipleShippingAddressNotSupportedIssueEnumSchema: Schema<MultipleShippingAddressNotSupportedIssueEnum> = stringEnum(MultipleShippingAddressNotSupportedIssueEnum);
