/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MultipleItemCategoriesDescriptionEnum
 */
export enum MultipleItemCategoriesDescriptionEnum {
  EnumForAGivenPurchaseUnitTheItemscategoryCouldBeEitherPHYSICALGOODSAndorDIGITALGOODSOrJustDONATIONItemscategoryAsDONATIONCannotBeCombinedWithItemsWithEitherPHYSICALGOODSOrDIGITALGOODS = 'For a given \'purchase_unit\' the \'items.category\' could be either "PHYSICAL_GOODS" and/or "DIGITAL_GOODS" or just "DONATION".  \'items.category\' as "DONATION" cannot be combined with items with either "PHYSICAL_GOODS" or "DIGITAL_GOODS".',
}

/**
 * Schema for MultipleItemCategoriesDescriptionEnum
 */
export const multipleItemCategoriesDescriptionEnumSchema: Schema<MultipleItemCategoriesDescriptionEnum> = stringEnum(MultipleItemCategoriesDescriptionEnum);
