/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  MultipleItemCategoriesDescriptionEnum,
  multipleItemCategoriesDescriptionEnumSchema,
} from './multipleItemCategoriesDescriptionEnum';
import {
  MultipleItemCategoriesIssueEnum,
  multipleItemCategoriesIssueEnumSchema,
} from './multipleItemCategoriesIssueEnum';

export interface MULTIPLEITEMCATEGORIES {
  issue?: MultipleItemCategoriesIssueEnum;
  description?: MultipleItemCategoriesDescriptionEnum;
}

export const mULTIPLEITEMCATEGORIESSchema: Schema<MULTIPLEITEMCATEGORIES> = object(
  {
    issue: ['issue', optional(multipleItemCategoriesIssueEnumSchema)],
    description: [
      'description',
      optional(multipleItemCategoriesDescriptionEnumSchema),
    ],
  }
);
