/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  ErrMerchInitMultiUnitsNotSupportedEnum,
  errMerchInitMultiUnitsNotSupportedEnumSchema,
} from './errMerchInitMultiUnitsNotSupportedEnum';
import {
  MerchantInitiatedMultiplePurchaseUnitsIssueEnum,
  merchantInitiatedMultiplePurchaseUnitsIssueEnumSchema,
} from './merchantInitiatedMultiplePurchaseUnitsIssueEnum';

export interface MULTIPURCHASEUNITSERROR {
  issue?: MerchantInitiatedMultiplePurchaseUnitsIssueEnum;
  description?: ErrMerchInitMultiUnitsNotSupportedEnum;
}

export const mULTIPURCHASEUNITSERRORSchema: Schema<MULTIPURCHASEUNITSERROR> = object(
  {
    issue: [
      'issue',
      optional(merchantInitiatedMultiplePurchaseUnitsIssueEnumSchema),
    ],
    description: [
      'description',
      optional(errMerchInitMultiUnitsNotSupportedEnumSchema),
    ],
  }
);
