/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MultipleShippingOptionSelectedDescriptionEnum
 */
export enum MultipleShippingOptionSelectedDescriptionEnum {
  EnumOnlyOneShippingoptionCanBeSetToSelectedTrue = 'Only one shipping.option can be set to \'selected = true\'.',
}

/**
 * Schema for MultipleShippingOptionSelectedDescriptionEnum
 */
export const multipleShippingOptionSelectedDescriptionEnumSchema: Schema<MultipleShippingOptionSelectedDescriptionEnum> = stringEnum(MultipleShippingOptionSelectedDescriptionEnum);
