/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for MultipleShippingOptionSelectedIssueEnum
 */
export enum MultipleShippingOptionSelectedIssueEnum {
  MULTIPLESHIPPINGOPTIONSELECTED = 'MULTIPLE_SHIPPING_OPTION_SELECTED',
}

/**
 * Schema for MultipleShippingOptionSelectedIssueEnum
 */
export const multipleShippingOptionSelectedIssueEnumSchema: Schema<MultipleShippingOptionSelectedIssueEnum> = stringEnum(MultipleShippingOptionSelectedIssueEnum);
