/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ExchangeRate, exchangeRateSchema } from './exchangeRate';
import { Money, moneySchema } from './money';

/** The net amount. Returned when the currency of the refund is different from the currency of the PayPal account where the merchant holds their funds. */
export interface NetAmountBreakdownItem {
  /** The net amount debited from the merchant's PayPal account. */
  payableAmount?: Money;
  /** The converted payable amount. */
  convertedAmount?: Money;
  /** The exchange rate that determines the amount that was debited from the merchant's PayPal account. */
  exchangeRate?: ExchangeRate;
}

export const netAmountBreakdownItemSchema: Schema<NetAmountBreakdownItem> = object(
  {
    payableAmount: ['payable_amount', optional(lazy(() => moneySchema))],
    convertedAmount: ['converted_amount', optional(lazy(() => moneySchema))],
    exchangeRate: ['exchange_rate', optional(lazy(() => exchangeRateSchema))],
  }
);
