/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEnabledToVaultPaymentSource1IssueEnum
 */
export enum NotEnabledToVaultPaymentSource1IssueEnum {
  NOTENABLEDTOVAULTPAYMENTSOURCE = 'NOT_ENABLED_TO_VAULT_PAYMENT_SOURCE',
}

/**
 * Schema for NotEnabledToVaultPaymentSource1IssueEnum
 */
export const notEnabledToVaultPaymentSource1IssueEnumSchema: Schema<NotEnabledToVaultPaymentSource1IssueEnum> = stringEnum(NotEnabledToVaultPaymentSource1IssueEnum);
