/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEnabledForGooglePayDescriptionEnum
 */
export enum NotEnabledForGooglePayDescriptionEnum {
  EnumTheAPICallerAndorPayeeIsNotSetupToBeAbleToProcessGooglePayPleaseContactYourAccountManager = 'The \'API caller\' and/or \'payee\' is not setup to be able to process google pay. Please contact your Account Manager.',
}

/**
 * Schema for NotEnabledForGooglePayDescriptionEnum
 */
export const notEnabledForGooglePayDescriptionEnumSchema: Schema<NotEnabledForGooglePayDescriptionEnum> = stringEnum(NotEnabledForGooglePayDescriptionEnum);
