/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEnabledForBankProcessingIssueEnum
 */
export enum NotEnabledForBankProcessingIssueEnum {
  NOTENABLEDFORBANKPROCESSING = 'NOT_ENABLED_FOR_BANK_PROCESSING',
}

/**
 * Schema for NotEnabledForBankProcessingIssueEnum
 */
export const notEnabledForBankProcessingIssueEnumSchema: Schema<NotEnabledForBankProcessingIssueEnum> = stringEnum(NotEnabledForBankProcessingIssueEnum);
