/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEnabledForApplePayIssueEnum
 */
export enum NotEnabledForApplePayIssueEnum {
  NOTENABLEDFORAPPLEPAY = 'NOT_ENABLED_FOR_APPLE_PAY',
}

/**
 * Schema for NotEnabledForApplePayIssueEnum
 */
export const notEnabledForApplePayIssueEnumSchema: Schema<NotEnabledForApplePayIssueEnum> = stringEnum(NotEnabledForApplePayIssueEnum);
