/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEnabledToVaultPaymentSourceDescriptionEnum
 */
export enum NotEnabledToVaultPaymentSourceDescriptionEnum {
  EnumTheAPICallerOrTheMerchantOnWhoseBehalfTheAPICallIsInitiatedIsNotAllowedToVaultTheGivenSourcePleaseContactPayPalCustomerSupportForAssistance = 'The API caller or the merchant on whose behalf the API call is initiated is not allowed to vault the given source. Please contact PayPal customer support for assistance.',
}

/**
 * Schema for NotEnabledToVaultPaymentSourceDescriptionEnum
 */
export const notEnabledToVaultPaymentSourceDescriptionEnumSchema: Schema<NotEnabledToVaultPaymentSourceDescriptionEnum> = stringEnum(NotEnabledToVaultPaymentSourceDescriptionEnum);
