/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEligibleForTokenProcessingDescription2Enum
 */
export enum NotEligibleForTokenProcessingDescription2Enum {
  EnumAPICallerIsNotEnabledToProcessPaymentsWithTheSpecifiedTypeOfTokenPleaseContactCustomerSupportToRequestPermissionsToProcessTransactionsWithThisTypeOfToken = 'API caller is not enabled to process payments with the specified type of token. Please contact customer support to request permissions to process transactions with this type of token.',
}

/**
 * Schema for NotEligibleForTokenProcessingDescription2Enum
 */
export const notEligibleForTokenProcessingDescription2EnumSchema: Schema<NotEligibleForTokenProcessingDescription2Enum> = stringEnum(NotEligibleForTokenProcessingDescription2Enum);
