/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEligibleForPnrefProcessingIssueEnum
 */
export enum NotEligibleForPnrefProcessingIssueEnum {
  NOTELIGIBLEFORPNREFPROCESSING = 'NOT_ELIGIBLE_FOR_PNREF_PROCESSING',
}

/**
 * Schema for NotEligibleForPnrefProcessingIssueEnum
 */
export const notEligibleForPnrefProcessingIssueEnumSchema: Schema<NotEligibleForPnrefProcessingIssueEnum> = stringEnum(NotEligibleForPnrefProcessingIssueEnum);
