/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEnabledForCardProcessingIssueEnum
 */
export enum NotEnabledForCardProcessingIssueEnum {
  NOTENABLEDFORCARDPROCESSING = 'NOT_ENABLED_FOR_CARD_PROCESSING',
}

/**
 * Schema for NotEnabledForCardProcessingIssueEnum
 */
export const notEnabledForCardProcessingIssueEnumSchema: Schema<NotEnabledForCardProcessingIssueEnum> = stringEnum(NotEnabledForCardProcessingIssueEnum);
