/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  NotEligibleForPnrefProcessing1DescriptionEnum,
  notEligibleForPnrefProcessing1DescriptionEnumSchema,
} from './notEligibleForPnrefProcessing1DescriptionEnum';
import {
  NotEligibleForPnrefProcessing1IssueEnum,
  notEligibleForPnrefProcessing1IssueEnumSchema,
} from './notEligibleForPnrefProcessing1IssueEnum';

export interface NOTELIGIBLEFORPNREFPROCESSINGERROR {
  issue?: NotEligibleForPnrefProcessing1IssueEnum;
  description?: NotEligibleForPnrefProcessing1DescriptionEnum;
}

export const nOTELIGIBLEFORPNREFPROCESSINGERRORSchema: Schema<NOTELIGIBLEFORPNREFPROCESSINGERROR> = object(
  {
    issue: ['issue', optional(notEligibleForPnrefProcessing1IssueEnumSchema)],
    description: [
      'description',
      optional(notEligibleForPnrefProcessing1DescriptionEnumSchema),
    ],
  }
);
