/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotEnabledForApplePayDescriptionEnum
 */
export enum NotEnabledForApplePayDescriptionEnum {
  EnumTheAPICallerAndorPayeeIsNotSetupToBeAbleToProcessApplePayPleaseContactYourAccountManager = 'The \'API caller\' and/or \'payee\' is not setup to be able to process apple pay. Please contact your Account Manager.',
}

/**
 * Schema for NotEnabledForApplePayDescriptionEnum
 */
export const notEnabledForApplePayDescriptionEnumSchema: Schema<NotEnabledForApplePayDescriptionEnum> = stringEnum(NotEnabledForApplePayDescriptionEnum);
