/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  NotEnabledToVaultPaymentSource1DescriptionEnum,
  notEnabledToVaultPaymentSource1DescriptionEnumSchema,
} from './notEnabledToVaultPaymentSource1DescriptionEnum';
import {
  NotEnabledToVaultPaymentSource1IssueEnum,
  notEnabledToVaultPaymentSource1IssueEnumSchema,
} from './notEnabledToVaultPaymentSource1IssueEnum';

export interface NOTENABLEDTOVAULTPAYMENTSOURCEERROR {
  issue?: NotEnabledToVaultPaymentSource1IssueEnum;
  description?: NotEnabledToVaultPaymentSource1DescriptionEnum;
}

export const nOTENABLEDTOVAULTPAYMENTSOURCEERRORSchema: Schema<NOTENABLEDTOVAULTPAYMENTSOURCEERROR> = object(
  {
    issue: ['issue', optional(notEnabledToVaultPaymentSource1IssueEnumSchema)],
    description: [
      'description',
      optional(notEnabledToVaultPaymentSource1DescriptionEnumSchema),
    ],
  }
);
