/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotPatchableIssueEnum
 */
export enum NotPatchableIssueEnum {
  NOTPATCHABLE = 'NOT_PATCHABLE',
}

/**
 * Schema for NotPatchableIssueEnum
 */
export const notPatchableIssueEnumSchema: Schema<NotPatchableIssueEnum> = stringEnum(NotPatchableIssueEnum);
