/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for NotSupportedIssueEnum
 */
export enum NotSupportedIssueEnum {
  NOTSUPPORTED = 'NOT_SUPPORTED',
}

/**
 * Schema for NotSupportedIssueEnum
 */
export const notSupportedIssueEnumSchema: Schema<NotSupportedIssueEnum> = stringEnum(NotSupportedIssueEnum);
