/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  NotSupportedDescriptionEnum,
  notSupportedDescriptionEnumSchema,
} from './notSupportedDescriptionEnum';
import {
  NotSupportedIssueEnum,
  notSupportedIssueEnumSchema,
} from './notSupportedIssueEnum';

export interface NOTSUPPORTED {
  issue?: NotSupportedIssueEnum;
  description?: NotSupportedDescriptionEnum;
}

export const nOTSUPPORTEDSchema: Schema<NOTSUPPORTED> = object({
  issue: ['issue', optional(notSupportedIssueEnumSchema)],
  description: ['description', optional(notSupportedDescriptionEnumSchema)],
});
