/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OAuthScopeEnum
 */
export enum OAuthScopeEnum {
  HttpsUriPaypalComServicesPaymentsPayment = 'https://uri.paypal.com/services/payments/payment',
  HttpsUriPaypalComServicesPaymentsPaymentReferenceTransaction = 'https://uri.paypal.com/services/payments/payment/reference-transaction',
  HttpsUriPaypalComServicesPaymentsInitiatepayment = 'https://uri.paypal.com/services/payments/initiatepayment',
  HttpsUriPaypalComServicesPaymentsOrdersClientSideIntegration = 'https://uri.paypal.com/services/payments/orders/client-side-integration',
  HttpsUriPaypalComServicesPaymentsPaymentAuthcapture = 'https://uri.paypal.com/services/payments/payment/authcapture',
  HttpsUriPaypalComServicesPaymentsRefund = 'https://uri.paypal.com/services/payments/refund',
  HttpsUriPaypalComServicesPaymentsNonReferencedCredit = 'https://uri.paypal.com/services/payments/non-referenced-credit',
  HttpsUriPaypalComServicesPaymentsRealtimepayment = 'https://uri.paypal.com/services/payments/realtimepayment',
  HttpsUriPaypalComServicesPaymentsReversepayment = 'https://uri.paypal.com/services/payments/reversepayment',
  HttpsUriPaypalComServicesVaultPaymentTokensReadwrite = 'https://uri.paypal.com/services/vault/payment-tokens/readwrite',
  HttpsUriPaypalComServicesVaultPaymentTokensRead = 'https://uri.paypal.com/services/vault/payment-tokens/read',
  HttpsUriPaypalComServicesVaultCustomersRead = 'https://uri.paypal.com/services/vault/customers/read',
  HttpsUriPaypalComServicesVaultCustomersReadwrite = 'https://uri.paypal.com/services/vault/customers/readwrite',
}

/**
 * Schema for OAuthScopeEnum
 */
export const oAuthScopeEnumSchema: Schema<OAuthScopeEnum> = stringEnum(OAuthScopeEnum);
