/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OAuthScopeOauth2Enum
 */
export enum OAuthScopeOauth2Enum {
  HttpsUriPaypalComServicesPaymentsPayment = 'https://uri.paypal.com/services/payments/payment',
  HttpsUriPaypalComServicesPaymentsPaymentReferenceTransaction = 'https://uri.paypal.com/services/payments/payment/reference-transaction',
  HttpsUriPaypalComServicesPaymentsInitiatepayment = 'https://uri.paypal.com/services/payments/initiatepayment',
  HttpsUriPaypalComServicesPaymentsOrdersClientSideIntegration = 'https://uri.paypal.com/services/payments/orders/client-side-integration',
  HttpsUriPaypalComServicesPaymentsPaymentAuthcapture = 'https://uri.paypal.com/services/payments/payment/authcapture',
  HttpsUriPaypalComServicesPaymentsRefund = 'https://uri.paypal.com/services/payments/refund',
  HttpsUriPaypalComServicesPaymentsNonReferencedCredit = 'https://uri.paypal.com/services/payments/non-referenced-credit',
  HttpsUriPaypalComServicesPaymentsRealtimepayment = 'https://uri.paypal.com/services/payments/realtimepayment',
  HttpsUriPaypalComServicesPaymentsReversepayment = 'https://uri.paypal.com/services/payments/reversepayment',
}

/**
 * Schema for OAuthScopeOauth2Enum
 */
export const oAuthScopeOauth2EnumSchema: Schema<OAuthScopeOauth2Enum> = stringEnum(OAuthScopeOauth2Enum);
