/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  OneOfParametersRequired1DescriptionEnum,
  oneOfParametersRequired1DescriptionEnumSchema,
} from './oneOfParametersRequired1DescriptionEnum';
import {
  OneOfParametersRequired1IssueEnum,
  oneOfParametersRequired1IssueEnumSchema,
} from './oneOfParametersRequired1IssueEnum';

export interface ONEOFPARAMETERSREQUIREDERROR {
  issue?: OneOfParametersRequired1IssueEnum;
  description?: OneOfParametersRequired1DescriptionEnum;
}

export const oNEOFPARAMETERSREQUIREDERRORSchema: Schema<ONEOFPARAMETERSREQUIREDERROR> = object(
  {
    issue: ['issue', optional(oneOfParametersRequired1IssueEnumSchema)],
    description: [
      'description',
      optional(oneOfParametersRequired1DescriptionEnumSchema),
    ],
  }
);
