/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  OrdersCapture422IssuesItems,
  ordersCapture422IssuesItemsSchema,
} from './containers/ordersCapture422IssuesItems';

export interface OrdersCapture422 {
  issues?: OrdersCapture422IssuesItems[];
}

export const ordersCapture422Schema: Schema<OrdersCapture422> = object({
  issues: [
    'issues',
    optional(array(lazy(() => ordersCapture422IssuesItemsSchema))),
  ],
});
