/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderAlreadyAuthorized1DescriptionEnum
 */
export enum OrderAlreadyAuthorized1DescriptionEnum {
  EnumOrderAlreadyAuthorizedIfIntentAUTHORIZEOnlyOneAuthorizationPerOrderIsAllowed = 'Order already authorized.If \'intent=AUTHORIZE\' only one authorization per order is allowed.',
}

/**
 * Schema for OrderAlreadyAuthorized1DescriptionEnum
 */
export const orderAlreadyAuthorized1DescriptionEnumSchema: Schema<OrderAlreadyAuthorized1DescriptionEnum> = stringEnum(OrderAlreadyAuthorized1DescriptionEnum);
