/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  ConsentNeededIssueEnum,
  consentNeededIssueEnumSchema,
} from './consentNeededIssueEnum';

export interface OrdersCapture403IssuesItems {
  issue?: ConsentNeededIssueEnum;
  description?: ConsentNeededIssueEnum;
}

export const ordersCapture403IssuesItemsSchema: Schema<OrdersCapture403IssuesItems> = object(
  {
    issue: ['issue', optional(consentNeededIssueEnumSchema)],
    description: ['description', optional(consentNeededIssueEnumSchema)],
  }
);
