/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderAlreadyAuthorized1IssueEnum
 */
export enum OrderAlreadyAuthorized1IssueEnum {
  ORDERALREADYAUTHORIZED = 'ORDER_ALREADY_AUTHORIZED',
}

/**
 * Schema for OrderAlreadyAuthorized1IssueEnum
 */
export const orderAlreadyAuthorized1IssueEnumSchema: Schema<OrderAlreadyAuthorized1IssueEnum> = stringEnum(OrderAlreadyAuthorized1IssueEnum);
