/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  OrderCompleteOnPaymentApprovalDescriptionEnum,
  orderCompleteOnPaymentApprovalDescriptionEnumSchema,
} from './orderCompleteOnPaymentApprovalDescriptionEnum';
import {
  OrderCompleteOnPaymentApprovalIssueEnum,
  orderCompleteOnPaymentApprovalIssueEnumSchema,
} from './orderCompleteOnPaymentApprovalIssueEnum';

export interface ORDERCOMPLETEONPAYMENTAPPROVAL {
  issue?: OrderCompleteOnPaymentApprovalIssueEnum;
  description?: OrderCompleteOnPaymentApprovalDescriptionEnum;
}

export const oRDERCOMPLETEONPAYMENTAPPROVALSchema: Schema<ORDERCOMPLETEONPAYMENTAPPROVAL> = object(
  {
    issue: ['issue', optional(orderCompleteOnPaymentApprovalIssueEnumSchema)],
    description: [
      'description',
      optional(orderCompleteOnPaymentApprovalDescriptionEnumSchema),
    ],
  }
);
