/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CaptureStatusNotValidDescriptionEnum,
  captureStatusNotValidDescriptionEnumSchema,
} from './captureStatusNotValidDescriptionEnum';
import {
  CaptureStatusNotValidIssueEnum,
  captureStatusNotValidIssueEnumSchema,
} from './captureStatusNotValidIssueEnum';

export interface OrdersTrackCreate422IssuesItems {
  issue?: CaptureStatusNotValidIssueEnum;
  description?: CaptureStatusNotValidDescriptionEnum;
}

export const ordersTrackCreate422IssuesItemsSchema: Schema<OrdersTrackCreate422IssuesItems> = object(
  {
    issue: ['issue', optional(captureStatusNotValidIssueEnumSchema)],
    description: [
      'description',
      optional(captureStatusNotValidDescriptionEnumSchema),
    ],
  }
);
