/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  OrdersAuthorize403IssuesItems,
  ordersAuthorize403IssuesItemsSchema,
} from './containers/ordersAuthorize403IssuesItems';

export interface OrdersAuthorize403 {
  issues?: OrdersAuthorize403IssuesItems[];
}

export const ordersAuthorize403Schema: Schema<OrdersAuthorize403> = object({
  issues: [
    'issues',
    optional(array(lazy(() => ordersAuthorize403IssuesItemsSchema))),
  ],
});
