/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderCompletionInProgressDescriptionEnum
 */
export enum OrderCompletionInProgressDescriptionEnum {
  EnumTheOrderWasCreatedWithProcessingInstructionOfORDERCOMPLETEONPAYMENTAPPROVALTheCustomerHasApprovedThePaymentAndPayPalIsStillInTheProcessOfCapturingTheOrderOnYourBehalfAsInstructedPleaseTryYourRequestAgain = 'The order was created with processing_instruction of ORDER_COMPLETE_ON_PAYMENT_APPROVAL. The customer has approved the payment and PayPal is still in the process of capturing the order on your behalf as instructed. Please try your request again.',
}

/**
 * Schema for OrderCompletionInProgressDescriptionEnum
 */
export const orderCompletionInProgressDescriptionEnumSchema: Schema<OrderCompletionInProgressDescriptionEnum> = stringEnum(OrderCompletionInProgressDescriptionEnum);
