/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import {
  OrdersCapture403IssuesItems,
  ordersCapture403IssuesItemsSchema,
} from './containers/ordersCapture403IssuesItems';

export interface OrdersCapture403 {
  issues?: OrdersCapture403IssuesItems[];
}

export const ordersCapture403Schema: Schema<OrdersCapture403> = object({
  issues: [
    'issues',
    optional(array(lazy(() => ordersCapture403IssuesItemsSchema))),
  ],
});
