/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { LinkDescription, linkDescriptionSchema } from './linkDescription';
import { OrderStatusEnum, orderStatusEnumSchema } from './orderStatusEnum';
import { Payer, payerSchema } from './payer';
import {
  PaymentIntentCheckoutEnum,
  paymentIntentCheckoutEnumSchema,
} from './paymentIntentCheckoutEnum';
import {
  PaymentSourceDetails,
  paymentSourceDetailsSchema,
} from './paymentSourceDetails';
import {
  ProcessingInstructionEnum,
  processingInstructionEnumSchema,
} from './processingInstructionEnum';
import { PurchaseUnit, purchaseUnitSchema } from './purchaseUnit';

/** The order details. */
export interface Order {
  /** The date and time when the transaction occurred, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). */
  createTime?: string;
  /** The date and time when the transaction was last updated, in [Internet date and time format](https://tools.ietf.org/html/rfc3339#section-5.6). */
  updateTime?: string;
  /** The ID of the order. */
  id?: string;
  /** The payment source used to fund the payment. */
  paymentSource?: PaymentSourceDetails;
  /** The intent to either capture payment immediately or authorize a payment for an order after order creation. */
  intent?: PaymentIntentCheckoutEnum;
  /** The instruction to process an order. */
  processingInstruction?: ProcessingInstructionEnum;
  /** DEPRECATED. The customer is also known as the payer. The Payer object was intended to only be used with the `payment_source.paypal` object. In order to make this design more clear, the details in the `payer` object are now available under `payment_source.paypal`. Please use `payment_source.paypal`. */
  payer?: Payer;
  /** An array of purchase units. Each purchase unit establishes a contract between a customer and merchant. Each purchase unit represents either a full or partial order that the customer intends to purchase from the merchant. */
  purchaseUnits?: PurchaseUnit[];
  status?: OrderStatusEnum;
  /** An array of request-related HATEOAS links. To complete payer approval, use the `approve` link to redirect the payer. The API caller has 3 hours (default setting, this which can be changed by your account manager to 24/48/72 hours to accommodate your use case) from the time the order is created, to redirect your payer. Once redirected, the API caller has 3 hours for the payer to approve the order and either authorize or capture the order. If you are not using the PayPal JavaScript SDK to initiate PayPal Checkout (in context) ensure that you include `application_context.return_url` is specified or you will get "We're sorry, Things don't appear to be working at the moment" after the payer approves the payment. */
  links?: LinkDescription[];
}

export const orderSchema: Schema<Order> = object({
  createTime: ['create_time', optional(string())],
  updateTime: ['update_time', optional(string())],
  id: ['id', optional(string())],
  paymentSource: [
    'payment_source',
    optional(lazy(() => paymentSourceDetailsSchema)),
  ],
  intent: ['intent', optional(paymentIntentCheckoutEnumSchema)],
  processingInstruction: [
    'processing_instruction',
    optional(processingInstructionEnumSchema),
  ],
  payer: ['payer', optional(lazy(() => payerSchema))],
  purchaseUnits: [
    'purchase_units',
    optional(array(lazy(() => purchaseUnitSchema))),
  ],
  status: ['status', optional(orderStatusEnumSchema)],
  links: ['links', optional(array(lazy(() => linkDescriptionSchema)))],
});
