/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for OrderAlreadyCaptured1IssueEnum
 */
export enum OrderAlreadyCaptured1IssueEnum {
  ORDERALREADYCAPTURED = 'ORDER_ALREADY_CAPTURED',
}

/**
 * Schema for OrderAlreadyCaptured1IssueEnum
 */
export const orderAlreadyCaptured1IssueEnumSchema: Schema<OrderAlreadyCaptured1IssueEnum> = stringEnum(OrderAlreadyCaptured1IssueEnum);
