/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** Information used to pay using P24(Przelewy24). */
export interface P24PaymentObject {
  /** The name of the account holder associated with this payment method. */
  name?: string;
  /** The email address of the account holder associated with this payment method. */
  email?: string;
  /** The [two-character ISO-3166-1 country code](/docs/integration/direct/rest/country-codes/) of the bank. */
  countryCode?: string;
  /** P24 generated payment description. */
  paymentDescriptor?: string;
  /** Numeric identifier of the payment scheme or bank used for the payment. */
  methodId?: string;
  /** Friendly name of the payment scheme or bank used for the payment. */
  methodDescription?: string;
}

export const p24PaymentObjectSchema: Schema<P24PaymentObject> = object({
  name: ['name', optional(string())],
  email: ['email', optional(string())],
  countryCode: ['country_code', optional(string())],
  paymentDescriptor: ['payment_descriptor', optional(string())],
  methodId: ['method_id', optional(string())],
  methodDescription: ['method_description', optional(string())],
});
