/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PatchPathRequired1IssueEnum
 */
export enum PatchPathRequired1IssueEnum {
  PATCHPATHREQUIRED = 'PATCH_PATH_REQUIRED',
}

/**
 * Schema for PatchPathRequired1IssueEnum
 */
export const patchPathRequired1IssueEnumSchema: Schema<PatchPathRequired1IssueEnum> = stringEnum(PatchPathRequired1IssueEnum);
