/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayerAccountRestricted2IssueEnum
 */
export enum PayerAccountRestricted2IssueEnum {
  PAYERACCOUNTRESTRICTED = 'PAYER_ACCOUNT_RESTRICTED',
}

/**
 * Schema for PayerAccountRestricted2IssueEnum
 */
export const payerAccountRestricted2IssueEnumSchema: Schema<PayerAccountRestricted2IssueEnum> = stringEnum(PayerAccountRestricted2IssueEnum);
