/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

/** The customer who approves and pays for the order. The customer is also known as the payer. */
export interface PayerBase {
  /** The email address of the payer. */
  emailAddress?: string;
  /** The PayPal-assigned ID for the payer. */
  payerId?: string;
}

export const payerBaseSchema: Schema<PayerBase> = object({
  emailAddress: ['email_address', optional(string())],
  payerId: ['payer_id', optional(string())],
});
