/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayerAccountLockedOrClosed2IssueEnum
 */
export enum PayerAccountLockedOrClosed2IssueEnum {
  PAYERACCOUNTLOCKEDORCLOSED = 'PAYER_ACCOUNT_LOCKED_OR_CLOSED',
}

/**
 * Schema for PayerAccountLockedOrClosed2IssueEnum
 */
export const payerAccountLockedOrClosed2IssueEnumSchema: Schema<PayerAccountLockedOrClosed2IssueEnum> = stringEnum(PayerAccountLockedOrClosed2IssueEnum);
