/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeeAccountRestrictedIssueEnum
 */
export enum PayeeAccountRestrictedIssueEnum {
  PAYEEACCOUNTRESTRICTED = 'PAYEE_ACCOUNT_RESTRICTED',
}

/**
 * Schema for PayeeAccountRestrictedIssueEnum
 */
export const payeeAccountRestrictedIssueEnumSchema: Schema<PayeeAccountRestrictedIssueEnum> = stringEnum(PayeeAccountRestrictedIssueEnum);
