/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeeAccountInvalidDescriptionEnum
 */
export enum PayeeAccountInvalidDescriptionEnum {
  EnumPayeeAccountSpecifiedIsInvalidPleaseCheckThePayeeemailAddressOrPayeemerchantIdSpecifiedAndTryAgainEnsureThatEitherPayeemerchantIdOrPayeeemailAddressIsSpecified = 'Payee account specified is invalid. Please check the `payee.email_address` or `payee.merchant_id` specified and try again. Ensure that either  `payee.merchant_id` or `payee.email_address` is specified.',
}

/**
 * Schema for PayeeAccountInvalidDescriptionEnum
 */
export const payeeAccountInvalidDescriptionEnumSchema: Schema<PayeeAccountInvalidDescriptionEnum> = stringEnum(PayeeAccountInvalidDescriptionEnum);
