/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PayerAccountLockedOrClosed2DescriptionEnum,
  payerAccountLockedOrClosed2DescriptionEnumSchema,
} from './payerAccountLockedOrClosed2DescriptionEnum';
import {
  PayerAccountLockedOrClosed2IssueEnum,
  payerAccountLockedOrClosed2IssueEnumSchema,
} from './payerAccountLockedOrClosed2IssueEnum';

export interface PAYERACCOUNTLOCKEDORCLOSEDERRORRESPONSE {
  issue?: PayerAccountLockedOrClosed2IssueEnum;
  description?: PayerAccountLockedOrClosed2DescriptionEnum;
}

export const pAYERACCOUNTLOCKEDORCLOSEDERRORRESPONSESchema: Schema<PAYERACCOUNTLOCKEDORCLOSEDERRORRESPONSE> = object(
  {
    issue: ['issue', optional(payerAccountLockedOrClosed2IssueEnumSchema)],
    description: [
      'description',
      optional(payerAccountLockedOrClosed2DescriptionEnumSchema),
    ],
  }
);
