/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayerActionRequiredIssueEnum
 */
export enum PayerActionRequiredIssueEnum {
  PAYERACTIONREQUIRED = 'PAYER_ACTION_REQUIRED',
}

/**
 * Schema for PayerActionRequiredIssueEnum
 */
export const payerActionRequiredIssueEnumSchema: Schema<PayerActionRequiredIssueEnum> = stringEnum(PayerActionRequiredIssueEnum);
