/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeeAccountNotVerifiedDescriptionEnum
 */
export enum PayeeAccountNotVerifiedDescriptionEnum {
  EnumPayeeHasNotVerifiedTheirAccountWithPayPalTheSelectedPaymentMethodRequiresTheRecipientToHaveAVerifiedPayPalAccountBeforeTransactionsCanBeProcessedOnTheirBehalf = 'Payee has not verified their account with PayPal. The selected payment method requires the recipient to have a verified PayPal account before transactions can be processed on their behalf.',
}

/**
 * Schema for PayeeAccountNotVerifiedDescriptionEnum
 */
export const payeeAccountNotVerifiedDescriptionEnumSchema: Schema<PayeeAccountNotVerifiedDescriptionEnum> = stringEnum(PayeeAccountNotVerifiedDescriptionEnum);
