/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PayerCannotPay2DescriptionEnum,
  payerCannotPay2DescriptionEnumSchema,
} from './payerCannotPay2DescriptionEnum';
import {
  PayerCannotPay2IssueEnum,
  payerCannotPay2IssueEnumSchema,
} from './payerCannotPay2IssueEnum';

export interface PAYERCANNOTPAYERRORRESPONSE {
  issue?: PayerCannotPay2IssueEnum;
  description?: PayerCannotPay2DescriptionEnum;
}

export const pAYERCANNOTPAYERRORRESPONSESchema: Schema<PAYERCANNOTPAYERRORRESPONSE> = object(
  {
    issue: ['issue', optional(payerCannotPay2IssueEnumSchema)],
    description: [
      'description',
      optional(payerCannotPay2DescriptionEnumSchema),
    ],
  }
);
