/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayerCannotPayThemselvesErrorEnum
 */
export enum PayerCannotPayThemselvesErrorEnum {
  EnumThePayerCannotPayThemselvesTheRecipientAccountOfThePlatformFeesMustBeDifferentFromThePayerAccount = 'The payer cannot pay themselves. The recipient account of the platform fees must be different from the payer account.',
}

/**
 * Schema for PayerCannotPayThemselvesErrorEnum
 */
export const payerCannotPayThemselvesErrorEnumSchema: Schema<PayerCannotPayThemselvesErrorEnum> = stringEnum(PayerCannotPayThemselvesErrorEnum);
