/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeeBlockedTransaction1DescriptionEnum
 */
export enum PayeeBlockedTransaction1DescriptionEnum {
  EnumTheFraudSettingsForThisSellerAreSuchThatThisPaymentCannotBeExecuted = 'The Fraud settings for this seller are such that this payment cannot be executed.',
}

/**
 * Schema for PayeeBlockedTransaction1DescriptionEnum
 */
export const payeeBlockedTransaction1DescriptionEnumSchema: Schema<PayeeBlockedTransaction1DescriptionEnum> = stringEnum(PayeeBlockedTransaction1DescriptionEnum);
