/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PayerAccountLockedOrClosed1DescriptionEnum,
  payerAccountLockedOrClosed1DescriptionEnumSchema,
} from './payerAccountLockedOrClosed1DescriptionEnum';
import {
  PayerAccountLockedOrClosed1IssueEnum,
  payerAccountLockedOrClosed1IssueEnumSchema,
} from './payerAccountLockedOrClosed1IssueEnum';

export interface PAYERACCOUNTLOCKEDORCLOSEDERROR {
  issue?: PayerAccountLockedOrClosed1IssueEnum;
  description?: PayerAccountLockedOrClosed1DescriptionEnum;
}

export const pAYERACCOUNTLOCKEDORCLOSEDERRORSchema: Schema<PAYERACCOUNTLOCKEDORCLOSEDERROR> = object(
  {
    issue: ['issue', optional(payerAccountLockedOrClosed1IssueEnumSchema)],
    description: [
      'description',
      optional(payerAccountLockedOrClosed1DescriptionEnumSchema),
    ],
  }
);
