/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeeAccountRestrictedDescriptionEnum
 */
export enum PayeeAccountRestrictedDescriptionEnum {
  EnumTheMerchantAccountIsRestricted = 'The merchant account is restricted.',
}

/**
 * Schema for PayeeAccountRestrictedDescriptionEnum
 */
export const payeeAccountRestrictedDescriptionEnumSchema: Schema<PayeeAccountRestrictedDescriptionEnum> = stringEnum(PayeeAccountRestrictedDescriptionEnum);
