/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PayeeFxRateIdExpired3DescriptionEnum,
  payeeFxRateIdExpired3DescriptionEnumSchema,
} from './payeeFxRateIdExpired3DescriptionEnum';
import {
  PayeeFxRateIdExpired3IssueEnum,
  payeeFxRateIdExpired3IssueEnumSchema,
} from './payeeFxRateIdExpired3IssueEnum';

export interface PAYEEFXRATEIDEXPIREDERRORRESPONSE {
  issue?: PayeeFxRateIdExpired3IssueEnum;
  description?: PayeeFxRateIdExpired3DescriptionEnum;
}

export const pAYEEFXRATEIDEXPIREDERRORRESPONSESchema: Schema<PAYEEFXRATEIDEXPIREDERRORRESPONSE> = object(
  {
    issue: ['issue', optional(payeeFxRateIdExpired3IssueEnumSchema)],
    description: [
      'description',
      optional(payeeFxRateIdExpired3DescriptionEnumSchema),
    ],
  }
);
