/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeeBlockedTransaction1IssueEnum
 */
export enum PayeeBlockedTransaction1IssueEnum {
  PAYEEBLOCKEDTRANSACTION = 'PAYEE_BLOCKED_TRANSACTION',
}

/**
 * Schema for PayeeBlockedTransaction1IssueEnum
 */
export const payeeBlockedTransaction1IssueEnumSchema: Schema<PayeeBlockedTransaction1IssueEnum> = stringEnum(PayeeBlockedTransaction1IssueEnum);
