/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PayeeFxRateIdExpired1DescriptionEnum,
  payeeFxRateIdExpired1DescriptionEnumSchema,
} from './payeeFxRateIdExpired1DescriptionEnum';
import {
  PayeeFxRateIdExpired1IssueEnum,
  payeeFxRateIdExpired1IssueEnumSchema,
} from './payeeFxRateIdExpired1IssueEnum';

export interface PayeeFXRateIDExpired1 {
  issue?: PayeeFxRateIdExpired1IssueEnum;
  description?: PayeeFxRateIdExpired1DescriptionEnum;
}

export const payeeFXRateIDExpired1Schema: Schema<PayeeFXRateIDExpired1> = object(
  {
    issue: ['issue', optional(payeeFxRateIdExpired1IssueEnumSchema)],
    description: [
      'description',
      optional(payeeFxRateIdExpired1DescriptionEnumSchema),
    ],
  }
);
