/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeePreferredPaymentMethodEnum
 */
export enum PayeePreferredPaymentMethodEnum {
  UNRESTRICTED = 'UNRESTRICTED',
  IMMEDIATEPAYMENTREQUIRED = 'IMMEDIATE_PAYMENT_REQUIRED',
}

/**
 * Schema for PayeePreferredPaymentMethodEnum
 */
export const payeePreferredPaymentMethodEnumSchema: Schema<PayeePreferredPaymentMethodEnum> = stringEnum(PayeePreferredPaymentMethodEnum);
