/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeeAccountNotVerifiedIssueEnum
 */
export enum PayeeAccountNotVerifiedIssueEnum {
  PAYEEACCOUNTNOTVERIFIED = 'PAYEE_ACCOUNT_NOT_VERIFIED',
}

/**
 * Schema for PayeeAccountNotVerifiedIssueEnum
 */
export const payeeAccountNotVerifiedIssueEnumSchema: Schema<PayeeAccountNotVerifiedIssueEnum> = stringEnum(PayeeAccountNotVerifiedIssueEnum);
