/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PayeeFxRateIdExpired3IssueEnum
 */
export enum PayeeFxRateIdExpired3IssueEnum {
  PAYEEFXRATEIDEXPIRED = 'PAYEE_FX_RATE_ID_EXPIRED',
}

/**
 * Schema for PayeeFxRateIdExpired3IssueEnum
 */
export const payeeFxRateIdExpired3IssueEnumSchema: Schema<PayeeFxRateIdExpired3IssueEnum> = stringEnum(PayeeFxRateIdExpired3IssueEnum);
