/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentSourceNotSupportedDescriptionEnum
 */
export enum PaymentSourceNotSupportedDescriptionEnum {
  EnumThePayerSelectedMethodOfPaymentIsNotSupportedWhenMultiplePurchaseUnitsAreSpecifiedForAnOrder = 'The payer selected method of payment is not supported when multiple purchase units are specified for an Order.',
}

/**
 * Schema for PaymentSourceNotSupportedDescriptionEnum
 */
export const paymentSourceNotSupportedDescriptionEnumSchema: Schema<PaymentSourceNotSupportedDescriptionEnum> = stringEnum(PaymentSourceNotSupportedDescriptionEnum);
