/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PaymentSourceDeclinedByProcessor1DescriptionEnum,
  paymentSourceDeclinedByProcessor1DescriptionEnumSchema,
} from './paymentSourceDeclinedByProcessor1DescriptionEnum';
import {
  PaymentSourceDeclinedByProcessor1IssueEnum,
  paymentSourceDeclinedByProcessor1IssueEnumSchema,
} from './paymentSourceDeclinedByProcessor1IssueEnum';

export interface PAYMENTSOURCEDECLINEDBYPROCESSORERROR {
  issue?: PaymentSourceDeclinedByProcessor1IssueEnum;
  description?: PaymentSourceDeclinedByProcessor1DescriptionEnum;
}

export const pAYMENTSOURCEDECLINEDBYPROCESSORERRORSchema: Schema<PAYMENTSOURCEDECLINEDBYPROCESSORERROR> = object(
  {
    issue: [
      'issue',
      optional(paymentSourceDeclinedByProcessor1IssueEnumSchema),
    ],
    description: [
      'description',
      optional(paymentSourceDeclinedByProcessor1DescriptionEnumSchema),
    ],
  }
);
