/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PaymentSourceCannotBeUsed1DescriptionEnum,
  paymentSourceCannotBeUsed1DescriptionEnumSchema,
} from './paymentSourceCannotBeUsed1DescriptionEnum';
import {
  PaymentSourceCannotBeUsed1IssueEnum,
  paymentSourceCannotBeUsed1IssueEnumSchema,
} from './paymentSourceCannotBeUsed1IssueEnum';

export interface PAYMENTSOURCECANNOTBEUSEDERROR {
  issue?: PaymentSourceCannotBeUsed1IssueEnum;
  description?: PaymentSourceCannotBeUsed1DescriptionEnum;
}

export const pAYMENTSOURCECANNOTBEUSEDERRORSchema: Schema<PAYMENTSOURCECANNOTBEUSEDERROR> = object(
  {
    issue: ['issue', optional(paymentSourceCannotBeUsed1IssueEnumSchema)],
    description: [
      'description',
      optional(paymentSourceCannotBeUsed1DescriptionEnumSchema),
    ],
  }
);
