/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentSourceMismatch2IssueEnum
 */
export enum PaymentSourceMismatch2IssueEnum {
  PAYMENTSOURCEMISMATCH = 'PAYMENT_SOURCE_MISMATCH',
}

/**
 * Schema for PaymentSourceMismatch2IssueEnum
 */
export const paymentSourceMismatch2IssueEnumSchema: Schema<PaymentSourceMismatch2IssueEnum> = stringEnum(PaymentSourceMismatch2IssueEnum);
