/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PaymentSourceInfoCannotBeVerified1IssueEnum,
  paymentSourceInfoCannotBeVerified1IssueEnumSchema,
} from './paymentSourceInfoCannotBeVerified1IssueEnum';
import {
  UnverifiedPaymentSourceAndAddressCombinationEnum,
  unverifiedPaymentSourceAndAddressCombinationEnumSchema,
} from './unverifiedPaymentSourceAndAddressCombinationEnum';

export interface PAYMENTSOURCEINFOCANNOTBEVERIFIEDERROR {
  issue?: PaymentSourceInfoCannotBeVerified1IssueEnum;
  description?: UnverifiedPaymentSourceAndAddressCombinationEnum;
}

export const pAYMENTSOURCEINFOCANNOTBEVERIFIEDERRORSchema: Schema<PAYMENTSOURCEINFOCANNOTBEVERIFIEDERROR> = object(
  {
    issue: [
      'issue',
      optional(paymentSourceInfoCannotBeVerified1IssueEnumSchema),
    ],
    description: [
      'description',
      optional(unverifiedPaymentSourceAndAddressCombinationEnumSchema),
    ],
  }
);
