/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { ApplePayResponse, applePayResponseSchema } from './applePayResponse';
import { BankResponse, bankResponseSchema } from './bankResponse';
import {
  CardResponsePaymentMethodTokens,
  cardResponsePaymentMethodTokensSchema,
} from './cardResponsePaymentMethodTokens';
import {
  PayPalWalletResponsePaymentMethodTokens,
  payPalWalletResponsePaymentMethodTokensSchema,
} from './payPalWalletResponsePaymentMethodTokens';
import { VenmoResponse, venmoResponseSchema } from './venmoResponse';

/** The vaulted payment method details. */
export interface PaymentTokenResponsePaymentSource {
  /** Full representation of a Card Payment Token. */
  card?: CardResponsePaymentMethodTokens;
  /** Full representation of a PayPal Payment Token. */
  paypal?: PayPalWalletResponsePaymentMethodTokens;
  /** Full representation of a Venmo Payment Token. */
  venmo?: VenmoResponse;
  /** A resource representing a response for Apple Pay. */
  applePay?: ApplePayResponse;
  /** Full representation of a Bank Payment Token. */
  bank?: BankResponse;
}

export const paymentTokenResponsePaymentSourceSchema: Schema<PaymentTokenResponsePaymentSource> = object(
  {
    card: ['card', optional(lazy(() => cardResponsePaymentMethodTokensSchema))],
    paypal: [
      'paypal',
      optional(lazy(() => payPalWalletResponsePaymentMethodTokensSchema)),
    ],
    venmo: ['venmo', optional(lazy(() => venmoResponseSchema))],
    applePay: ['apple_pay', optional(lazy(() => applePayResponseSchema))],
    bank: ['bank', optional(lazy(() => bankResponseSchema))],
  }
);
