/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentCardTypeEnum
 */
export enum PaymentCardTypeEnum {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  PREPAID = 'PREPAID',
  UNKNOWN = 'UNKNOWN',
}

/**
 * Schema for PaymentCardTypeEnum
 */
export const paymentCardTypeEnumSchema: Schema<PaymentCardTypeEnum> = stringEnum(PaymentCardTypeEnum);
