/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PaymentSourceMismatch2DescriptionEnum,
  paymentSourceMismatch2DescriptionEnumSchema,
} from './paymentSourceMismatch2DescriptionEnum';
import {
  PaymentSourceMismatch2IssueEnum,
  paymentSourceMismatch2IssueEnumSchema,
} from './paymentSourceMismatch2IssueEnum';

export interface PAYMENTSOURCEMISMATCHERRORRESPONSE {
  issue?: PaymentSourceMismatch2IssueEnum;
  description?: PaymentSourceMismatch2DescriptionEnum;
}

export const pAYMENTSOURCEMISMATCHERRORRESPONSESchema: Schema<PAYMENTSOURCEMISMATCHERRORRESPONSE> = object(
  {
    issue: ['issue', optional(paymentSourceMismatch2IssueEnumSchema)],
    description: [
      'description',
      optional(paymentSourceMismatch2DescriptionEnumSchema),
    ],
  }
);
