/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaymentAdviceCodeEnum
 */
export enum PaymentAdviceCodeEnum {
  Enum01 = '01',
  Enum02 = '02',
  Enum03 = '03',
  Enum21 = '21',
}

/**
 * Schema for PaymentAdviceCodeEnum
 */
export const paymentAdviceCodeEnumSchema: Schema<PaymentAdviceCodeEnum> = stringEnum(PaymentAdviceCodeEnum);
