/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  NotEligiblePaypalTxIdProcessingIssueEnum,
  notEligiblePaypalTxIdProcessingIssueEnumSchema,
} from './notEligiblePaypalTxIdProcessingIssueEnum';
import {
  PaypalTxIdProcessingPermissionNeededDescEnum,
  paypalTxIdProcessingPermissionNeededDescEnumSchema,
} from './paypalTxIdProcessingPermissionNeededDescEnum';

export interface PAYPALIDPROCESSINGINELIGIBILITYERRORRESPONSE {
  issue?: NotEligiblePaypalTxIdProcessingIssueEnum;
  description?: PaypalTxIdProcessingPermissionNeededDescEnum;
}

export const pAYPALIDPROCESSINGINELIGIBILITYERRORRESPONSESchema: Schema<PAYPALIDPROCESSINGINELIGIBILITYERRORRESPONSE> = object(
  {
    issue: ['issue', optional(notEligiblePaypalTxIdProcessingIssueEnumSchema)],
    description: [
      'description',
      optional(paypalTxIdProcessingPermissionNeededDescEnumSchema),
    ],
  }
);
