/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PaypalTransactionIdExpiredDescriptionEnum,
  paypalTransactionIdExpiredDescriptionEnumSchema,
} from './paypalTransactionIdExpiredDescriptionEnum';
import {
  PaypalTransactionIdExpiredIssueEnum,
  paypalTransactionIdExpiredIssueEnumSchema,
} from './paypalTransactionIdExpiredIssueEnum';

export interface PAYPALTRANSACTIONIDEXPIRED {
  issue?: PaypalTransactionIdExpiredIssueEnum;
  description?: PaypalTransactionIdExpiredDescriptionEnum;
}

export const pAYPALTRANSACTIONIDEXPIREDSchema: Schema<PAYPALTRANSACTIONIDEXPIRED> = object(
  {
    issue: ['issue', optional(paypalTransactionIdExpiredIssueEnumSchema)],
    description: [
      'description',
      optional(paypalTransactionIdExpiredDescriptionEnumSchema),
    ],
  }
);
