/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  PayPalSCustomerDataRecords,
  payPalSCustomerDataRecordsSchema,
} from './payPalSCustomerDataRecords';
import {
  VaultedPayPalWalletCommonAttributes,
  vaultedPayPalWalletCommonAttributesSchema,
} from './vaultedPayPalWalletCommonAttributes';

/** Additional attributes associated with the use of this PayPal Wallet. */
export interface PayPalWalletAttributes {
  /** The details about a customer in PayPal's system of record. */
  customer?: PayPalSCustomerDataRecords;
  /** Attributes used to provide the instructions during vaulting of the PayPal Wallet. */
  vault?: VaultedPayPalWalletCommonAttributes;
}

export const payPalWalletAttributesSchema: Schema<PayPalWalletAttributes> = object(
  {
    customer: [
      'customer',
      optional(lazy(() => payPalSCustomerDataRecordsSchema)),
    ],
    vault: [
      'vault',
      optional(lazy(() => vaultedPayPalWalletCommonAttributesSchema)),
    ],
  }
);
