/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaypalTransactionIdExpiredDescriptionEnum
 */
export enum PaypalTransactionIdExpiredDescriptionEnum {
  EnumSpecifiedPaypalTransactionIdHasExpiredPayPalTransactionIDExpires4YearsAfterTheDateOfTheInitialTransaction = 'Specified `paypal_transaction_id` has expired. PayPal transaction ID expires 4 years after the date of the initial transaction.',
}

/**
 * Schema for PaypalTransactionIdExpiredDescriptionEnum
 */
export const paypalTransactionIdExpiredDescriptionEnumSchema: Schema<PaypalTransactionIdExpiredDescriptionEnum> = stringEnum(PaypalTransactionIdExpiredDescriptionEnum);
