/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PaypalTransactionIdExpired1IssueEnum
 */
export enum PaypalTransactionIdExpired1IssueEnum {
  PAYPALTRANSACTIONIDEXPIRED = 'PAYPAL_TRANSACTION_ID_EXPIRED',
}

/**
 * Schema for PaypalTransactionIdExpired1IssueEnum
 */
export const paypalTransactionIdExpired1IssueEnumSchema: Schema<PaypalTransactionIdExpired1IssueEnum> = stringEnum(PaypalTransactionIdExpired1IssueEnum);
