/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import { Phone, phoneSchema } from './phone';

export interface PaypalWalletResponseAllof2 {
  /** The account identifier for a PayPal account. */
  accountId?: string;
  /** The phone number, in its canonical international [E.164 numbering plan format](https://www.itu.int/rec/T-REC-E.164/en). */
  phoneNumber?: Phone;
}

export const paypalWalletResponseAllof2Schema: Schema<PaypalWalletResponseAllof2> = object(
  {
    accountId: ['account_id', optional(string())],
    phoneNumber: ['phone_number', optional(lazy(() => phoneSchema))],
  }
);
