/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PermissionDeniedForDonationItemsIssueEnum
 */
export enum PermissionDeniedForDonationItemsIssueEnum {
  PERMISSIONDENIEDFORDONATIONITEMS = 'PERMISSION_DENIED_FOR_DONATION_ITEMS',
}

/**
 * Schema for PermissionDeniedForDonationItemsIssueEnum
 */
export const permissionDeniedForDonationItemsIssueEnumSchema: Schema<PermissionDeniedForDonationItemsIssueEnum> = stringEnum(PermissionDeniedForDonationItemsIssueEnum);
