/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PermissionDeniedDescriptionEnum,
  permissionDeniedDescriptionEnumSchema,
} from './permissionDeniedDescriptionEnum';
import {
  PermissionDeniedIssueEnum,
  permissionDeniedIssueEnumSchema,
} from './permissionDeniedIssueEnum';

export interface PERMISSIONDENIED {
  issue?: PermissionDeniedIssueEnum;
  description?: PermissionDeniedDescriptionEnum;
}

export const pERMISSIONDENIEDSchema: Schema<PERMISSIONDENIED> = object({
  issue: ['issue', optional(permissionDeniedIssueEnumSchema)],
  description: ['description', optional(permissionDeniedDescriptionEnumSchema)],
});
