/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PermissionDenied2DescriptionEnum,
  permissionDenied2DescriptionEnumSchema,
} from './permissionDenied2DescriptionEnum';
import {
  PermissionDenied2IssueEnum,
  permissionDenied2IssueEnumSchema,
} from './permissionDenied2IssueEnum';

export interface PERMISSIONDENIEDRESULT {
  issue?: PermissionDenied2IssueEnum;
  description?: PermissionDenied2DescriptionEnum;
}

export const pERMISSIONDENIEDRESULTSchema: Schema<PERMISSIONDENIEDRESULT> = object(
  {
    issue: ['issue', optional(permissionDenied2IssueEnumSchema)],
    description: [
      'description',
      optional(permissionDenied2DescriptionEnumSchema),
    ],
  }
);
