/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PermissionDeniedForDonationItems1IssueEnum
 */
export enum PermissionDeniedForDonationItems1IssueEnum {
  PERMISSIONDENIEDFORDONATIONITEMS = 'PERMISSION_DENIED_FOR_DONATION_ITEMS',
}

/**
 * Schema for PermissionDeniedForDonationItems1IssueEnum
 */
export const permissionDeniedForDonationItems1IssueEnumSchema: Schema<PermissionDeniedForDonationItems1IssueEnum> = stringEnum(PermissionDeniedForDonationItems1IssueEnum);
