/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PermissionDeniedForDonationItemsDescriptionEnum,
  permissionDeniedForDonationItemsDescriptionEnumSchema,
} from './permissionDeniedForDonationItemsDescriptionEnum';
import {
  PermissionDeniedForDonationItemsIssueEnum,
  permissionDeniedForDonationItemsIssueEnumSchema,
} from './permissionDeniedForDonationItemsIssueEnum';

export interface PERMISSIONDENIEDFORDONATIONITEMS {
  issue?: PermissionDeniedForDonationItemsIssueEnum;
  description?: PermissionDeniedForDonationItemsDescriptionEnum;
}

export const pERMISSIONDENIEDFORDONATIONITEMSSchema: Schema<PERMISSIONDENIEDFORDONATIONITEMS> = object(
  {
    issue: ['issue', optional(permissionDeniedForDonationItemsIssueEnumSchema)],
    description: [
      'description',
      optional(permissionDeniedForDonationItemsDescriptionEnumSchema),
    ],
  }
);
