/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PermissionDenied4IssueEnum
 */
export enum PermissionDenied4IssueEnum {
  PERMISSIONDENIED = 'PERMISSION_DENIED',
}

/**
 * Schema for PermissionDenied4IssueEnum
 */
export const permissionDenied4IssueEnumSchema: Schema<PermissionDenied4IssueEnum> = stringEnum(PermissionDenied4IssueEnum);
