/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PlatformFeesNotSupportedDescriptionEnum,
  platformFeesNotSupportedDescriptionEnumSchema,
} from './platformFeesNotSupportedDescriptionEnum';
import {
  PlatformFeesNotSupportedIssueEnum,
  platformFeesNotSupportedIssueEnumSchema,
} from './platformFeesNotSupportedIssueEnum';

export interface PLATFORMFEESNOTSUPPORTED {
  issue?: PlatformFeesNotSupportedIssueEnum;
  description?: PlatformFeesNotSupportedDescriptionEnum;
}

export const pLATFORMFEESNOTSUPPORTEDSchema: Schema<PLATFORMFEESNOTSUPPORTED> = object(
  {
    issue: ['issue', optional(platformFeesNotSupportedIssueEnumSchema)],
    description: [
      'description',
      optional(platformFeesNotSupportedDescriptionEnumSchema),
    ],
  }
);
