/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PlatformFeesNotSupported1DescriptionEnum
 */
export enum PlatformFeesNotSupported1DescriptionEnum {
  EnumTheAPICallerIsNotEnabledToProcessTransactionsBySpecifyingPlatformFeesPleaseWorkWithYourPayPalAccountManagerToEnableThisOptionForYourAccount = 'The API Caller is not enabled to process transactions by specifying \'platform_fees\'. Please work with your PayPal Account Manager to enable this option for your account.',
}

/**
 * Schema for PlatformFeesNotSupported1DescriptionEnum
 */
export const platformFeesNotSupported1DescriptionEnumSchema: Schema<PlatformFeesNotSupported1DescriptionEnum> = stringEnum(PlatformFeesNotSupported1DescriptionEnum);
