/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PnrefExpiredIssueEnum
 */
export enum PnrefExpiredIssueEnum {
  PNREFEXPIRED = 'PNREF_EXPIRED',
}

/**
 * Schema for PnrefExpiredIssueEnum
 */
export const pnrefExpiredIssueEnumSchema: Schema<PnrefExpiredIssueEnum> = stringEnum(PnrefExpiredIssueEnum);
