/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PnrefNotFoundDescriptionEnum,
  pnrefNotFoundDescriptionEnumSchema,
} from './pnrefNotFoundDescriptionEnum';
import {
  PnrefNotFoundIssueEnum,
  pnrefNotFoundIssueEnumSchema,
} from './pnrefNotFoundIssueEnum';

export interface PNREFNOTFOUND {
  issue?: PnrefNotFoundIssueEnum;
  description?: PnrefNotFoundDescriptionEnum;
}

export const pNREFNOTFOUNDSchema: Schema<PNREFNOTFOUND> = object({
  issue: ['issue', optional(pnrefNotFoundIssueEnumSchema)],
  description: ['description', optional(pnrefNotFoundDescriptionEnumSchema)],
});
