/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PostalCodeRequired1IssueEnum
 */
export enum PostalCodeRequired1IssueEnum {
  POSTALCODEREQUIRED = 'POSTAL_CODE_REQUIRED',
}

/**
 * Schema for PostalCodeRequired1IssueEnum
 */
export const postalCodeRequired1IssueEnumSchema: Schema<PostalCodeRequired1IssueEnum> = stringEnum(PostalCodeRequired1IssueEnum);
