/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PostalCodeRequired1DescriptionEnum,
  postalCodeRequired1DescriptionEnumSchema,
} from './postalCodeRequired1DescriptionEnum';
import {
  PostalCodeRequired1IssueEnum,
  postalCodeRequired1IssueEnumSchema,
} from './postalCodeRequired1IssueEnum';

export interface PostalCodeRequired1 {
  issue?: PostalCodeRequired1IssueEnum;
  description?: PostalCodeRequired1DescriptionEnum;
}

export const postalCodeRequired1Schema: Schema<PostalCodeRequired1> = object({
  issue: ['issue', optional(postalCodeRequired1IssueEnumSchema)],
  description: [
    'description',
    optional(postalCodeRequired1DescriptionEnumSchema),
  ],
});
