/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PostalCodeRequired1DescriptionEnum
 */
export enum PostalCodeRequired1DescriptionEnum {
  EnumTheSpecifiedCountryRequiresAPostalCode = 'The specified country requires a postal code.',
}

/**
 * Schema for PostalCodeRequired1DescriptionEnum
 */
export const postalCodeRequired1DescriptionEnumSchema: Schema<PostalCodeRequired1DescriptionEnum> = stringEnum(PostalCodeRequired1DescriptionEnum);
