/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PreferredShippingOptionAmountMismatch1IssueEnum
 */
export enum PreferredShippingOptionAmountMismatch1IssueEnum {
  PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH = 'PREFERRED_SHIPPING_OPTION_AMOUNT_MISMATCH',
}

/**
 * Schema for PreferredShippingOptionAmountMismatch1IssueEnum
 */
export const preferredShippingOptionAmountMismatch1IssueEnumSchema: Schema<PreferredShippingOptionAmountMismatch1IssueEnum> = stringEnum(PreferredShippingOptionAmountMismatch1IssueEnum);
