/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PreferredShippingOptionAmountMismatchIssueEnum
 */
export enum PreferredShippingOptionAmountMismatchIssueEnum {
  PREFERREDSHIPPINGOPTIONAMOUNTMISMATCH = 'PREFERRED_SHIPPING_OPTION_AMOUNT_MISMATCH',
}

/**
 * Schema for PreferredShippingOptionAmountMismatchIssueEnum
 */
export const preferredShippingOptionAmountMismatchIssueEnumSchema: Schema<PreferredShippingOptionAmountMismatchIssueEnum> = stringEnum(PreferredShippingOptionAmountMismatchIssueEnum);
