/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PreferredPaymentSourceMismatchDescriptionEnum
 */
export enum PreferredPaymentSourceMismatchDescriptionEnum {
  EnumPaymentSourceMustExactlyMatchThePreferredPaymentSourceThatWasProvidedDuringOrderCreation = 'Payment Source must exactly match the Preferred Payment Source that was provided during order creation.',
}

/**
 * Schema for PreferredPaymentSourceMismatchDescriptionEnum
 */
export const preferredPaymentSourceMismatchDescriptionEnumSchema: Schema<PreferredPaymentSourceMismatchDescriptionEnum> = stringEnum(PreferredPaymentSourceMismatchDescriptionEnum);
