/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PreferredPaymentSourceMismatchDescriptionEnum,
  preferredPaymentSourceMismatchDescriptionEnumSchema,
} from './preferredPaymentSourceMismatchDescriptionEnum';
import {
  PreferredPaymentSourceMismatchIssueEnum,
  preferredPaymentSourceMismatchIssueEnumSchema,
} from './preferredPaymentSourceMismatchIssueEnum';

export interface PREFERREDPAYMENTSOURCEMISMATCH {
  issue?: PreferredPaymentSourceMismatchIssueEnum;
  description?: PreferredPaymentSourceMismatchDescriptionEnum;
}

export const pREFERREDPAYMENTSOURCEMISMATCHSchema: Schema<PREFERREDPAYMENTSOURCEMISMATCH> = object(
  {
    issue: ['issue', optional(preferredPaymentSourceMismatchIssueEnumSchema)],
    description: [
      'description',
      optional(preferredPaymentSourceMismatchDescriptionEnumSchema),
    ],
  }
);
