/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  AuthorizationsVoid422IssuesItemsAnyof1DescriptionEnum,
  authorizationsVoid422IssuesItemsAnyof1DescriptionEnumSchema,
} from './authorizationsVoid422IssuesItemsAnyof1DescriptionEnum';
import {
  AuthorizationsVoid422IssuesItemsAnyof1IssueEnum,
  authorizationsVoid422IssuesItemsAnyof1IssueEnumSchema,
} from './authorizationsVoid422IssuesItemsAnyof1IssueEnum';

export interface PREVIOUSLYVOIDED {
  issue?: AuthorizationsVoid422IssuesItemsAnyof1IssueEnum;
  description?: AuthorizationsVoid422IssuesItemsAnyof1DescriptionEnum;
}

export const pREVIOUSLYVOIDEDSchema: Schema<PREVIOUSLYVOIDED> = object({
  issue: [
    'issue',
    optional(authorizationsVoid422IssuesItemsAnyof1IssueEnumSchema),
  ],
  description: [
    'description',
    optional(authorizationsVoid422IssuesItemsAnyof1DescriptionEnumSchema),
  ],
});
