/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PreviousTransactionReferenceVoided1DescriptionEnum,
  previousTransactionReferenceVoided1DescriptionEnumSchema,
} from './previousTransactionReferenceVoided1DescriptionEnum';
import {
  PreviousTransactionReferenceVoided1IssueEnum,
  previousTransactionReferenceVoided1IssueEnumSchema,
} from './previousTransactionReferenceVoided1IssueEnum';

export interface PREVIOUSTRANSACTIONREFERENCEVOIDEDERROR {
  issue?: PreviousTransactionReferenceVoided1IssueEnum;
  description?: PreviousTransactionReferenceVoided1DescriptionEnum;
}

export const pREVIOUSTRANSACTIONREFERENCEVOIDEDERRORSchema: Schema<PREVIOUSTRANSACTIONREFERENCEVOIDEDERROR> = object(
  {
    issue: [
      'issue',
      optional(previousTransactionReferenceVoided1IssueEnumSchema),
    ],
    description: [
      'description',
      optional(previousTransactionReferenceVoided1DescriptionEnumSchema),
    ],
  }
);
