/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PreviousRequestInProgressDescription1Enum
 */
export enum PreviousRequestInProgressDescription1Enum {
  EnumAPreviousRequestOnThisResourceIsCurrentlyInProgressPleaseWaitForSometimeAndTryAgainItIsBestToSpaceOutTheInitialAndTheSubsequentRequestsToAvoidReceivingThisError = 'A previous request on this resource is currently in progress. Please wait for sometime and try again. It is best to space out the initial and the subsequent request(s) to avoid receiving this error.',
}

/**
 * Schema for PreviousRequestInProgressDescription1Enum
 */
export const previousRequestInProgressDescription1EnumSchema: Schema<PreviousRequestInProgressDescription1Enum> = stringEnum(PreviousRequestInProgressDescription1Enum);
