/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PreviousTransactionReferenceChargebackIssueEnum
 */
export enum PreviousTransactionReferenceChargebackIssueEnum {
  PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK = 'PREVIOUS_TRANSACTION_REFERENCE_HAS_CHARGEBACK',
}

/**
 * Schema for PreviousTransactionReferenceChargebackIssueEnum
 */
export const previousTransactionReferenceChargebackIssueEnumSchema: Schema<PreviousTransactionReferenceChargebackIssueEnum> = stringEnum(PreviousTransactionReferenceChargebackIssueEnum);
