/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  PreviousTransactionReferenceChargebackIssueEnum,
  previousTransactionReferenceChargebackIssueEnumSchema,
} from './previousTransactionReferenceChargebackIssueEnum';
import {
  PrevTransRefChargebackDescEnum,
  prevTransRefChargebackDescEnumSchema,
} from './prevTransRefChargebackDescEnum';

export interface PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK {
  issue?: PreviousTransactionReferenceChargebackIssueEnum;
  description?: PrevTransRefChargebackDescEnum;
}

export const pREVIOUSTRANSACTIONREFERENCEHASCHARGEBACKSchema: Schema<PREVIOUSTRANSACTIONREFERENCEHASCHARGEBACK> = object(
  {
    issue: [
      'issue',
      optional(previousTransactionReferenceChargebackIssueEnumSchema),
    ],
    description: [
      'description',
      optional(prevTransRefChargebackDescEnumSchema),
    ],
  }
);
