/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReauthorizationNotSupportedIssueEnum
 */
export enum ReauthorizationNotSupportedIssueEnum {
  REAUTHORIZATIONNOTSUPPORTED = 'REAUTHORIZATION_NOT_SUPPORTED',
}

/**
 * Schema for ReauthorizationNotSupportedIssueEnum
 */
export const reauthorizationNotSupportedIssueEnumSchema: Schema<ReauthorizationNotSupportedIssueEnum> = stringEnum(ReauthorizationNotSupportedIssueEnum);
