/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReferenceIdNotFoundIssueEnum
 */
export enum ReferenceIdNotFoundIssueEnum {
  REFERENCEIDNOTFOUND = 'REFERENCE_ID_NOT_FOUND',
}

/**
 * Schema for ReferenceIdNotFoundIssueEnum
 */
export const referenceIdNotFoundIssueEnumSchema: Schema<ReferenceIdNotFoundIssueEnum> = stringEnum(ReferenceIdNotFoundIssueEnum);
