/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReferenceIdRequired1IssueEnum
 */
export enum ReferenceIdRequired1IssueEnum {
  REFERENCEIDREQUIRED = 'REFERENCE_ID_REQUIRED',
}

/**
 * Schema for ReferenceIdRequired1IssueEnum
 */
export const referenceIdRequired1IssueEnumSchema: Schema<ReferenceIdRequired1IssueEnum> = stringEnum(ReferenceIdRequired1IssueEnum);
