/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CapturesRefund422IssuesItemsAnyof7DescriptionEnum,
  capturesRefund422IssuesItemsAnyof7DescriptionEnumSchema,
} from './capturesRefund422IssuesItemsAnyof7DescriptionEnum';
import {
  CapturesRefund422IssuesItemsAnyof7IssueEnum,
  capturesRefund422IssuesItemsAnyof7IssueEnumSchema,
} from './capturesRefund422IssuesItemsAnyof7IssueEnum';

export interface REFUNDCAPTURECURRENCYMISMATCH {
  issue?: CapturesRefund422IssuesItemsAnyof7IssueEnum;
  description?: CapturesRefund422IssuesItemsAnyof7DescriptionEnum;
}

export const rEFUNDCAPTURECURRENCYMISMATCHSchema: Schema<REFUNDCAPTURECURRENCYMISMATCH> = object(
  {
    issue: [
      'issue',
      optional(capturesRefund422IssuesItemsAnyof7IssueEnumSchema),
    ],
    description: [
      'description',
      optional(capturesRefund422IssuesItemsAnyof7DescriptionEnumSchema),
    ],
  }
);
