/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CapturesRefund422IssuesItemsAnyof9DescriptionEnum,
  capturesRefund422IssuesItemsAnyof9DescriptionEnumSchema,
} from './capturesRefund422IssuesItemsAnyof9DescriptionEnum';
import {
  CapturesRefund422IssuesItemsAnyof9IssueEnum,
  capturesRefund422IssuesItemsAnyof9IssueEnumSchema,
} from './capturesRefund422IssuesItemsAnyof9IssueEnum';

export interface REFUNDTIMELIMITEXCEEDED {
  issue?: CapturesRefund422IssuesItemsAnyof9IssueEnum;
  description?: CapturesRefund422IssuesItemsAnyof9DescriptionEnum;
}

export const rEFUNDTIMELIMITEXCEEDEDSchema: Schema<REFUNDTIMELIMITEXCEEDED> = object(
  {
    issue: [
      'issue',
      optional(capturesRefund422IssuesItemsAnyof9IssueEnumSchema),
    ],
    description: [
      'description',
      optional(capturesRefund422IssuesItemsAnyof9DescriptionEnumSchema),
    ],
  }
);
