/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import { RefundReasonEnum, refundReasonEnumSchema } from './refundReasonEnum';

/** The details of the refund status. */
export interface RefundStatusDetails {
  /** The reason why the refund has the `PENDING` or `FAILED` status. */
  reason?: RefundReasonEnum;
}

export const refundStatusDetailsSchema: Schema<RefundStatusDetails> = object({
  reason: ['reason', optional(refundReasonEnumSchema)],
});
