/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  RequiredParameterForPaymentSourceDescriptionEnum,
  requiredParameterForPaymentSourceDescriptionEnumSchema,
} from './requiredParameterForPaymentSourceDescriptionEnum';
import {
  RequiredParameterForPaymentSourceIssueEnum,
  requiredParameterForPaymentSourceIssueEnumSchema,
} from './requiredParameterForPaymentSourceIssueEnum';

export interface REQUIREDPARAMETERFORPAYMENTSOURCE {
  issue?: RequiredParameterForPaymentSourceIssueEnum;
  description?: RequiredParameterForPaymentSourceDescriptionEnum;
}

export const rEQUIREDPARAMETERFORPAYMENTSOURCESchema: Schema<REQUIREDPARAMETERFORPAYMENTSOURCE> = object(
  {
    issue: [
      'issue',
      optional(requiredParameterForPaymentSourceIssueEnumSchema),
    ],
    description: [
      'description',
      optional(requiredParameterForPaymentSourceDescriptionEnumSchema),
    ],
  }
);
