/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ResourceNotFoundNameEnum
 */
export enum ResourceNotFoundNameEnum {
  RESOURCENOTFOUND = 'RESOURCE_NOT_FOUND',
}

/**
 * Schema for ResourceNotFoundNameEnum
 */
export const resourceNotFoundNameEnumSchema: Schema<ResourceNotFoundNameEnum> = stringEnum(ResourceNotFoundNameEnum);
