/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ReturnUrlRequiredIssueEnum
 */
export enum ReturnUrlRequiredIssueEnum {
  RETURNURLREQUIRED = 'RETURN_URL_REQUIRED',
}

/**
 * Schema for ReturnUrlRequiredIssueEnum
 */
export const returnUrlRequiredIssueEnumSchema: Schema<ReturnUrlRequiredIssueEnum> = stringEnum(ReturnUrlRequiredIssueEnum);
