/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  ReturnUrlRequired1DescriptionEnum,
  returnUrlRequired1DescriptionEnumSchema,
} from './returnUrlRequired1DescriptionEnum';
import {
  ReturnUrlRequired1IssueEnum,
  returnUrlRequired1IssueEnumSchema,
} from './returnUrlRequired1IssueEnum';

export interface RETURNURLREQUIREDERROR {
  issue?: ReturnUrlRequired1IssueEnum;
  description?: ReturnUrlRequired1DescriptionEnum;
}

export const rETURNURLREQUIREDERRORSchema: Schema<RETURNURLREQUIREDERROR> = object(
  {
    issue: ['issue', optional(returnUrlRequired1IssueEnumSchema)],
    description: [
      'description',
      optional(returnUrlRequired1DescriptionEnumSchema),
    ],
  }
);
