/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SaveOrderNotSupportedIssueEnum
 */
export enum SaveOrderNotSupportedIssueEnum {
  SAVEORDERNOTSUPPORTED = 'SAVE_ORDER_NOT_SUPPORTED',
}

/**
 * Schema for SaveOrderNotSupportedIssueEnum
 */
export const saveOrderNotSupportedIssueEnumSchema: Schema<SaveOrderNotSupportedIssueEnum> = stringEnum(SaveOrderNotSupportedIssueEnum);
