/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import {
  CardRequestPaymentMethodTokens,
  cardRequestPaymentMethodTokensSchema,
} from './cardRequestPaymentMethodTokens';
import {
  PayPalWalletRequest,
  payPalWalletRequestSchema,
} from './payPalWalletRequest';
import { TokenRequest, tokenRequestSchema } from './tokenRequest';
import { VenmoRequest, venmoRequestSchema } from './venmoRequest';

/** The payment method to vault with the instrument details. */
export interface SetupTokenRequestPaymentSource {
  /** A Resource representing a request to vault a Card. */
  card?: CardRequestPaymentMethodTokens;
  /** A resource representing a request to vault PayPal Wallet. */
  paypal?: PayPalWalletRequest;
  /** A resource representing a request to vault Venmo. */
  venmo?: VenmoRequest;
  /** The Tokenized Payment Source representing a Request to Vault a Token. */
  token?: TokenRequest;
}

export const setupTokenRequestPaymentSourceSchema: Schema<SetupTokenRequestPaymentSource> = object(
  {
    card: ['card', optional(lazy(() => cardRequestPaymentMethodTokensSchema))],
    paypal: ['paypal', optional(lazy(() => payPalWalletRequestSchema))],
    venmo: ['venmo', optional(lazy(() => venmoRequestSchema))],
    token: ['token', optional(lazy(() => tokenRequestSchema))],
  }
);
