/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SetupErrorForBank1DescriptionEnum
 */
export enum SetupErrorForBank1DescriptionEnum {
  EnumTheAPICallerAccountSetupForBankPaymentsIsIncompleteOrIncorrectPleaseContactYourPayPalAccountManager = 'The API Caller account setup, for bank payments, is incomplete or incorrect. Please contact your PayPal account manager.',
}

/**
 * Schema for SetupErrorForBank1DescriptionEnum
 */
export const setupErrorForBank1DescriptionEnumSchema: Schema<SetupErrorForBank1DescriptionEnum> = stringEnum(SetupErrorForBank1DescriptionEnum);
