/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for SetupErrorForBank1IssueEnum
 */
export enum SetupErrorForBank1IssueEnum {
  SETUPERRORFORBANK = 'SETUP_ERROR_FOR_BANK',
}

/**
 * Schema for SetupErrorForBank1IssueEnum
 */
export const setupErrorForBank1IssueEnumSchema: Schema<SetupErrorForBank1IssueEnum> = stringEnum(SetupErrorForBank1IssueEnum);
