/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  ShippingOptionNotSelected1DescriptionEnum,
  shippingOptionNotSelected1DescriptionEnumSchema,
} from './shippingOptionNotSelected1DescriptionEnum';
import {
  ShippingOptionNotSelected1IssueEnum,
  shippingOptionNotSelected1IssueEnumSchema,
} from './shippingOptionNotSelected1IssueEnum';

export interface ShippingOptionNotSelected1 {
  issue?: ShippingOptionNotSelected1IssueEnum;
  description?: ShippingOptionNotSelected1DescriptionEnum;
}

export const shippingOptionNotSelected1Schema: Schema<ShippingOptionNotSelected1> = object(
  {
    issue: ['issue', optional(shippingOptionNotSelected1IssueEnumSchema)],
    description: [
      'description',
      optional(shippingOptionNotSelected1DescriptionEnumSchema),
    ],
  }
);
