/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ShippingAddressInvalid1DescriptionEnum
 */
export enum ShippingAddressInvalid1DescriptionEnum {
  EnumProvidedShippingAddressIsInvalid = 'Provided shipping address is invalid.',
}

/**
 * Schema for ShippingAddressInvalid1DescriptionEnum
 */
export const shippingAddressInvalid1DescriptionEnumSchema: Schema<ShippingAddressInvalid1DescriptionEnum> = stringEnum(ShippingAddressInvalid1DescriptionEnum);
