/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ShipmentTrackingStatusEnum
 */
export enum ShipmentTrackingStatusEnum {
  CANCELLED = 'CANCELLED',
  DELIVERED = 'DELIVERED',
  LOCALPICKUP = 'LOCAL_PICKUP',
  ONHOLD = 'ON_HOLD',
  SHIPPED = 'SHIPPED',
  SHIPMENTCREATED = 'SHIPMENT_CREATED',
  DROPPEDOFF = 'DROPPED_OFF',
  INTRANSIT = 'IN_TRANSIT',
  RETURNED = 'RETURNED',
  LABELPRINTED = 'LABEL_PRINTED',
  ERROR = 'ERROR',
  UNCONFIRMED = 'UNCONFIRMED',
  PICKUPFAILED = 'PICKUP_FAILED',
  DELIVERYDELAYED = 'DELIVERY_DELAYED',
  DELIVERYSCHEDULED = 'DELIVERY_SCHEDULED',
  DELIVERYFAILED = 'DELIVERY_FAILED',
  INRETURN = 'INRETURN',
  INPROCESS = 'IN_PROCESS',
  NEW = 'NEW',
  VOID = 'VOID',
  PROCESSED = 'PROCESSED',
  NOTSHIPPED = 'NOT_SHIPPED',
  COMPLETED = 'COMPLETED',
}

/**
 * Schema for ShipmentTrackingStatusEnum
 */
export const shipmentTrackingStatusEnumSchema: Schema<ShipmentTrackingStatusEnum> = stringEnum(ShipmentTrackingStatusEnum);
