/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ShippingOptionNotSupportedIssueEnum
 */
export enum ShippingOptionNotSupportedIssueEnum {
  SHIPPINGOPTIONSNOTSUPPORTED = 'SHIPPING_OPTIONS_NOT_SUPPORTED',
}

/**
 * Schema for ShippingOptionNotSupportedIssueEnum
 */
export const shippingOptionNotSupportedIssueEnumSchema: Schema<ShippingOptionNotSupportedIssueEnum> = stringEnum(ShippingOptionNotSupportedIssueEnum);
