/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for ShippingOptionNotSelectedIssueEnum
 */
export enum ShippingOptionNotSelectedIssueEnum {
  SHIPPINGOPTIONNOTSELECTED = 'SHIPPING_OPTION_NOT_SELECTED',
}

/**
 * Schema for ShippingOptionNotSelectedIssueEnum
 */
export const shippingOptionNotSelectedIssueEnumSchema: Schema<ShippingOptionNotSelectedIssueEnum> = stringEnum(ShippingOptionNotSelectedIssueEnum);
