/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StandardEntryClassCodeEnum
 */
export enum StandardEntryClassCodeEnum {
  TEL = 'TEL',
  WEB = 'WEB',
  CCD = 'CCD',
  PPD = 'PPD',
}

/**
 * Schema for StandardEntryClassCodeEnum
 */
export const standardEntryClassCodeEnumSchema: Schema<StandardEntryClassCodeEnum> = stringEnum(StandardEntryClassCodeEnum);
