/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StoredPaymentUsageTypeEnum
 */
export enum StoredPaymentUsageTypeEnum {
  FIRST = 'FIRST',
  SUBSEQUENT = 'SUBSEQUENT',
  DERIVED = 'DERIVED',
}

/**
 * Schema for StoredPaymentUsageTypeEnum
 */
export const storedPaymentUsageTypeEnumSchema: Schema<StoredPaymentUsageTypeEnum> = stringEnum(StoredPaymentUsageTypeEnum);
