/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for StoredPaymentTypeEnum
 */
export enum StoredPaymentTypeEnum {
  ONETIME = 'ONE_TIME',
  RECURRING = 'RECURRING',
  UNSCHEDULED = 'UNSCHEDULED',
}

/**
 * Schema for StoredPaymentTypeEnum
 */
export const storedPaymentTypeEnumSchema: Schema<StoredPaymentTypeEnum> = stringEnum(StoredPaymentTypeEnum);
