/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxTotalRequiredDescriptionEnum
 */
export enum TaxTotalRequiredDescriptionEnum {
  EnumIfItemDetailsAreSpecifiedItemstaxTotalAndItemsquantityCorrespondingAmountbreakdowntaxTotalIsRequired = 'If item details are specified (items.tax_total and items.quantity) corresponding amount.breakdown.tax_total is required.',
}

/**
 * Schema for TaxTotalRequiredDescriptionEnum
 */
export const taxTotalRequiredDescriptionEnumSchema: Schema<TaxTotalRequiredDescriptionEnum> = stringEnum(TaxTotalRequiredDescriptionEnum);
