/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxTotalMismatchIssueEnum
 */
export enum TaxTotalMismatchIssueEnum {
  TAXTOTALMISMATCH = 'TAX_TOTAL_MISMATCH',
}

/**
 * Schema for TaxTotalMismatchIssueEnum
 */
export const taxTotalMismatchIssueEnumSchema: Schema<TaxTotalMismatchIssueEnum> = stringEnum(TaxTotalMismatchIssueEnum);
