/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  TaxTotalMismatch1DescriptionEnum,
  taxTotalMismatch1DescriptionEnumSchema,
} from './taxTotalMismatch1DescriptionEnum';
import {
  TaxTotalMismatch1IssueEnum,
  taxTotalMismatch1IssueEnumSchema,
} from './taxTotalMismatch1IssueEnum';

export interface TaxTotalMismatch1 {
  issue?: TaxTotalMismatch1IssueEnum;
  description?: TaxTotalMismatch1DescriptionEnum;
}

export const taxTotalMismatch1Schema: Schema<TaxTotalMismatch1> = object({
  issue: ['issue', optional(taxTotalMismatch1IssueEnumSchema)],
  description: [
    'description',
    optional(taxTotalMismatch1DescriptionEnumSchema),
  ],
});
