/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TaxTotalMismatch1DescriptionEnum
 */
export enum TaxTotalMismatch1DescriptionEnum {
  EnumShouldEqualSumOfTaxQuantityAcrossAllItemsForAGivenPurchaseUnit = 'Should equal sum of (tax * quantity) across all items for a given purchase_unit.',
}

/**
 * Schema for TaxTotalMismatch1DescriptionEnum
 */
export const taxTotalMismatch1DescriptionEnumSchema: Schema<TaxTotalMismatch1DescriptionEnum> = stringEnum(TaxTotalMismatch1DescriptionEnum);
