/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  TokenExpired1DescriptionEnum,
  tokenExpired1DescriptionEnumSchema,
} from './tokenExpired1DescriptionEnum';
import {
  TokenExpired1IssueEnum,
  tokenExpired1IssueEnumSchema,
} from './tokenExpired1IssueEnum';

export interface TOKENEXPIREDERROR {
  issue?: TokenExpired1IssueEnum;
  description?: TokenExpired1DescriptionEnum;
}

export const tOKENEXPIREDERRORSchema: Schema<TOKENEXPIREDERROR> = object({
  issue: ['issue', optional(tokenExpired1IssueEnumSchema)],
  description: ['description', optional(tokenExpired1DescriptionEnumSchema)],
});
