/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TokenIdNotFoundIssueEnum
 */
export enum TokenIdNotFoundIssueEnum {
  TOKENIDNOTFOUND = 'TOKEN_ID_NOT_FOUND',
}

/**
 * Schema for TokenIdNotFoundIssueEnum
 */
export const tokenIdNotFoundIssueEnumSchema: Schema<TokenIdNotFoundIssueEnum> = stringEnum(TokenIdNotFoundIssueEnum);
