/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TokenExpired2IssueEnum
 */
export enum TokenExpired2IssueEnum {
  TOKENEXPIRED = 'TOKEN_EXPIRED',
}

/**
 * Schema for TokenExpired2IssueEnum
 */
export const tokenExpired2IssueEnumSchema: Schema<TokenExpired2IssueEnum> = stringEnum(TokenExpired2IssueEnum);
