/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TokenIdNotFound1IssueEnum
 */
export enum TokenIdNotFound1IssueEnum {
  TOKENIDNOTFOUND = 'TOKEN_ID_NOT_FOUND',
}

/**
 * Schema for TokenIdNotFound1IssueEnum
 */
export const tokenIdNotFound1IssueEnumSchema: Schema<TokenIdNotFound1IssueEnum> = stringEnum(TokenIdNotFound1IssueEnum);
