/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  TransactionReceivingLimitExceeded1DescriptionEnum,
  transactionReceivingLimitExceeded1DescriptionEnumSchema,
} from './transactionReceivingLimitExceeded1DescriptionEnum';
import {
  TransactionReceivingLimitExceeded1IssueEnum,
  transactionReceivingLimitExceeded1IssueEnumSchema,
} from './transactionReceivingLimitExceeded1IssueEnum';

export interface TRANSACTIONRECEIVINGLIMITEXCEEDEDERROR {
  issue?: TransactionReceivingLimitExceeded1IssueEnum;
  description?: TransactionReceivingLimitExceeded1DescriptionEnum;
}

export const tRANSACTIONRECEIVINGLIMITEXCEEDEDERRORSchema: Schema<TRANSACTIONRECEIVINGLIMITEXCEEDEDERROR> = object(
  {
    issue: [
      'issue',
      optional(transactionReceivingLimitExceeded1IssueEnumSchema),
    ],
    description: [
      'description',
      optional(transactionReceivingLimitExceeded1DescriptionEnumSchema),
    ],
  }
);
