/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionReceivingLimitExceeded2IssueEnum
 */
export enum TransactionReceivingLimitExceeded2IssueEnum {
  TRANSACTIONRECEIVINGLIMITEXCEEDED = 'TRANSACTION_RECEIVING_LIMIT_EXCEEDED',
}

/**
 * Schema for TransactionReceivingLimitExceeded2IssueEnum
 */
export const transactionReceivingLimitExceeded2IssueEnumSchema: Schema<TransactionReceivingLimitExceeded2IssueEnum> = stringEnum(TransactionReceivingLimitExceeded2IssueEnum);
