/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionReceivingLimitExceededIssueEnum
 */
export enum TransactionReceivingLimitExceededIssueEnum {
  TRANSACTIONRECEIVINGLIMITEXCEEDED = 'TRANSACTION_RECEIVING_LIMIT_EXCEEDED',
}

/**
 * Schema for TransactionReceivingLimitExceededIssueEnum
 */
export const transactionReceivingLimitExceededIssueEnumSchema: Schema<TransactionReceivingLimitExceededIssueEnum> = stringEnum(TransactionReceivingLimitExceededIssueEnum);
