/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for TransactionRefused1DescriptionEnum
 */
export enum TransactionRefused1DescriptionEnum {
  EnumTheRequestWasRefused = 'The request was refused.',
}

/**
 * Schema for TransactionRefused1DescriptionEnum
 */
export const transactionRefused1DescriptionEnumSchema: Schema<TransactionRefused1DescriptionEnum> = stringEnum(TransactionRefused1DescriptionEnum);
