/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  CapturesRefund422IssuesItemsAnyof21DescriptionEnum,
  capturesRefund422IssuesItemsAnyof21DescriptionEnumSchema,
} from './capturesRefund422IssuesItemsAnyof21DescriptionEnum';
import {
  CapturesRefund422IssuesItemsAnyof21IssueEnum,
  capturesRefund422IssuesItemsAnyof21IssueEnumSchema,
} from './capturesRefund422IssuesItemsAnyof21IssueEnum';

export interface TRANSACTIONDISPUTED {
  issue?: CapturesRefund422IssuesItemsAnyof21IssueEnum;
  description?: CapturesRefund422IssuesItemsAnyof21DescriptionEnum;
}

export const tRANSACTIONDISPUTEDSchema: Schema<TRANSACTIONDISPUTED> = object({
  issue: [
    'issue',
    optional(capturesRefund422IssuesItemsAnyof21IssueEnumSchema),
  ],
  description: [
    'description',
    optional(capturesRefund422IssuesItemsAnyof21DescriptionEnumSchema),
  ],
});
