/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnauthorizedRequestNameEnum
 */
export enum UnauthorizedRequestNameEnum {
  AUTHENTICATIONFAILURE = 'AUTHENTICATION_FAILURE',
}

/**
 * Schema for UnauthorizedRequestNameEnum
 */
export const unauthorizedRequestNameEnumSchema: Schema<UnauthorizedRequestNameEnum> = stringEnum(UnauthorizedRequestNameEnum);
