/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ErrorDetails3, errorDetails3Schema } from './errorDetails3';
import {
  UnprocessableRequestmessageEnum,
  unprocessableRequestmessageEnumSchema,
} from './unprocessableRequestmessageEnum';
import {
  UnprocessableRequestNameEnum,
  unprocessableRequestNameEnumSchema,
} from './unprocessableRequestNameEnum';

export interface UnprocessableRequest {
  name?: UnprocessableRequestNameEnum;
  message?: UnprocessableRequestmessageEnum;
  issues?: ErrorDetails3[];
  /** The PayPal internal ID. Used for correlation purposes. */
  debugId?: string;
  /** The information link, or URI, that shows detailed information about this error for the developer. */
  informationLink?: string;
}

export const unprocessableRequestSchema: Schema<UnprocessableRequest> = object({
  name: ['name', optional(unprocessableRequestNameEnumSchema)],
  message: ['message', optional(unprocessableRequestmessageEnumSchema)],
  issues: ['issues', optional(array(lazy(() => errorDetails3Schema)))],
  debugId: ['debug_id', optional(string())],
  informationLink: ['information_link', optional(string())],
});
