/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnprocessableRequestNameEnum
 */
export enum UnprocessableRequestNameEnum {
  UNPROCESSABLEENTITY = 'UNPROCESSABLE_ENTITY',
}

/**
 * Schema for UnprocessableRequestNameEnum
 */
export const unprocessableRequestNameEnumSchema: Schema<UnprocessableRequestNameEnum> = stringEnum(UnprocessableRequestNameEnum);
