/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  UnsupportedPatchParameterValueDescriptionEnum,
  unsupportedPatchParameterValueDescriptionEnumSchema,
} from './unsupportedPatchParameterValueDescriptionEnum';
import {
  UnsupportedPatchParameterValueIssueEnum,
  unsupportedPatchParameterValueIssueEnumSchema,
} from './unsupportedPatchParameterValueIssueEnum';

export interface UNSUPPORTEDPATCHPARAMETERVALUE {
  issue?: UnsupportedPatchParameterValueIssueEnum;
  description?: UnsupportedPatchParameterValueDescriptionEnum;
}

export const uNSUPPORTEDPATCHPARAMETERVALUESchema: Schema<UNSUPPORTEDPATCHPARAMETERVALUE> = object(
  {
    issue: ['issue', optional(unsupportedPatchParameterValueIssueEnumSchema)],
    description: [
      'description',
      optional(unsupportedPatchParameterValueDescriptionEnumSchema),
    ],
  }
);
