/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnsupportedProcessingInstructionIssueEnum
 */
export enum UnsupportedProcessingInstructionIssueEnum {
  UNSUPPORTEDPROCESSINGINSTRUCTION = 'UNSUPPORTED_PROCESSING_INSTRUCTION',
}

/**
 * Schema for UnsupportedProcessingInstructionIssueEnum
 */
export const unsupportedProcessingInstructionIssueEnumSchema: Schema<UnsupportedProcessingInstructionIssueEnum> = stringEnum(UnsupportedProcessingInstructionIssueEnum);
