/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UnsupportedPatchParameterValueIssueEnum
 */
export enum UnsupportedPatchParameterValueIssueEnum {
  UNSUPPORTEDPATCHPARAMETERVALUE = 'UNSUPPORTED_PATCH_PARAMETER_VALUE',
}

/**
 * Schema for UnsupportedPatchParameterValueIssueEnum
 */
export const unsupportedPatchParameterValueIssueEnumSchema: Schema<UnsupportedPatchParameterValueIssueEnum> = stringEnum(UnsupportedPatchParameterValueIssueEnum);
