/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  UnsupportedProcessingInstruction1DescriptionEnum,
  unsupportedProcessingInstruction1DescriptionEnumSchema,
} from './unsupportedProcessingInstruction1DescriptionEnum';
import {
  UnsupportedProcessingInstruction1IssueEnum,
  unsupportedProcessingInstruction1IssueEnumSchema,
} from './unsupportedProcessingInstruction1IssueEnum';

export interface UNSUPPORTEDPROCESSINGINSTRUCTIONERROR {
  issue?: UnsupportedProcessingInstruction1IssueEnum;
  description?: UnsupportedProcessingInstruction1DescriptionEnum;
}

export const uNSUPPORTEDPROCESSINGINSTRUCTIONERRORSchema: Schema<UNSUPPORTEDPROCESSINGINSTRUCTIONERROR> = object(
  {
    issue: [
      'issue',
      optional(unsupportedProcessingInstruction1IssueEnumSchema),
    ],
    description: [
      'description',
      optional(unsupportedProcessingInstruction1DescriptionEnumSchema),
    ],
  }
);
