/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for UserActionEnum
 */
export enum UserActionEnum {
  CONTINUE = 'CONTINUE',
  PAYNOW = 'PAY_NOW',
}

/**
 * Schema for UserActionEnum
 */
export const userActionEnumSchema: Schema<UserActionEnum> = stringEnum(UserActionEnum);
