/**
 * Paypal Merged APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VaultInstructionRequired3DescriptionEnum
 */
export enum VaultInstructionRequired3DescriptionEnum {
  EnumVaultInstructionIsRequiredPleaseUseVaultstoreInVaultToProvideVaultInstruction = 'Vault instruction is required. Please use `vault.store_in_vault` to provide vault instruction.',
}

/**
 * Schema for VaultInstructionRequired3DescriptionEnum
 */
export const vaultInstructionRequired3DescriptionEnumSchema: Schema<VaultInstructionRequired3DescriptionEnum> = stringEnum(VaultInstructionRequired3DescriptionEnum);
