/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  VaultInstructionRequiredDescriptionEnum,
  vaultInstructionRequiredDescriptionEnumSchema,
} from './vaultInstructionRequiredDescriptionEnum';
import {
  VaultInstructionRequiredIssueEnum,
  vaultInstructionRequiredIssueEnumSchema,
} from './vaultInstructionRequiredIssueEnum';

export interface VAULTINSTRUCTIONREQUIRED {
  issue?: VaultInstructionRequiredIssueEnum;
  description?: VaultInstructionRequiredDescriptionEnum;
}

export const vAULTINSTRUCTIONREQUIREDSchema: Schema<VAULTINSTRUCTIONREQUIRED> = object(
  {
    issue: ['issue', optional(vaultInstructionRequiredIssueEnumSchema)],
    description: [
      'description',
      optional(vaultInstructionRequiredDescriptionEnumSchema),
    ],
  }
);
