/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema';
import {
  VaultInstructionRequired3DescriptionEnum,
  vaultInstructionRequired3DescriptionEnumSchema,
} from './vaultInstructionRequired3DescriptionEnum';
import {
  VaultInstructionRequired3IssueEnum,
  vaultInstructionRequired3IssueEnumSchema,
} from './vaultInstructionRequired3IssueEnum';

export interface VAULTINSTRUCTIONREQUIREDERRORRESPONSE {
  issue?: VaultInstructionRequired3IssueEnum;
  description?: VaultInstructionRequired3DescriptionEnum;
}

export const vAULTINSTRUCTIONREQUIREDERRORRESPONSESchema: Schema<VAULTINSTRUCTIONREQUIREDERRORRESPONSE> = object(
  {
    issue: ['issue', optional(vaultInstructionRequired3IssueEnumSchema)],
    description: [
      'description',
      optional(vaultInstructionRequired3DescriptionEnumSchema),
    ],
  }
);
