/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VaultInstructionRequired2IssueEnum
 */
export enum VaultInstructionRequired2IssueEnum {
  VAULTINSTRUCTIONREQUIRED = 'VAULT_INSTRUCTION_REQUIRED',
}

/**
 * Schema for VaultInstructionRequired2IssueEnum
 */
export const vaultInstructionRequired2IssueEnumSchema: Schema<VaultInstructionRequired2IssueEnum> = stringEnum(VaultInstructionRequired2IssueEnum);
