/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for VaultInstructionRequiredDescriptionEnum
 */
export enum VaultInstructionRequiredDescriptionEnum {
  EnumVaultInstructionIsRequiredPleaseUseVaultstoreInVaultToProvideVaultInstruction = 'Vault instruction is required. Please use `vault.store_in_vault` to provide vault instruction.',
}

/**
 * Schema for VaultInstructionRequiredDescriptionEnum
 */
export const vaultInstructionRequiredDescriptionEnumSchema: Schema<VaultInstructionRequiredDescriptionEnum> = stringEnum(VaultInstructionRequiredDescriptionEnum);
