/**
 * Merged ApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema';
import {
  VenmoWalletAttributes,
  venmoWalletAttributesSchema,
} from './venmoWalletAttributes';
import {
  VenmoWalletExperienceContext,
  venmoWalletExperienceContextSchema,
} from './venmoWalletExperienceContext';

/** Information needed to pay using Venmo. */
export interface VenmoPaymentRequestObject {
  /** The PayPal-generated ID for the saved Venmo wallet payment_source. This ID should be stored on the merchant's server so the saved payment source can be used for future transactions. */
  vaultId?: string;
  /** The email address of the payer. */
  emailAddress?: string;
  /** Customizes the buyer experience during the approval process for payment with Venmo.<blockquote><strong>Note:</strong> Partners and Marketplaces might configure <code>shipping_preference</code> during partner account setup, which overrides the request values.</blockquote> */
  experienceContext?: VenmoWalletExperienceContext;
  /** Additional attributes associated with the use of this wallet. */
  attributes?: VenmoWalletAttributes;
}

export const venmoPaymentRequestObjectSchema: Schema<VenmoPaymentRequestObject> = object(
  {
    vaultId: ['vault_id', optional(string())],
    emailAddress: ['email_address', optional(string())],
    experienceContext: [
      'experience_context',
      optional(lazy(() => venmoWalletExperienceContextSchema)),
    ],
    attributes: [
      'attributes',
      optional(lazy(() => venmoWalletAttributesSchema)),
    ],
  }
);
